- .github/workflows/publish-contract-deploy.yml
- Dockerfile
- _test/init_test_accounts.sh
- _test/phase_v1.mk
create docker image for gnoswap contract deployment
> Gsw 387 docker image

- README.md
- _test/live_test.mk
* modify README
* use absolute path for integration test
> Gsw 391 gnoswap readme

- _test/live_test.mk
- _test/phase_v1.mk
* makefiles use custom chainid
> [GSW-426] chore: makefile get chainid from environment variable

- gov/const.gno
- gov/gns_helper.gno
- gov/proposal_community_pool_spend.gno
- gov/proposal_mint.gno
- pool/_TEST_math_logic_test.gno
- pool/_TEST_math_logic_test.gnoa
- pool/_TEST_pool_creation_fee_test.gno
- pool/_TEST_pool_multi_lp_fee_api_test.gnoa
- pool/_TEST_pool_multi_lp_fee_test.gnoa
- pool/_TEST_pool_multi_lp_test.gnoa
- pool/_TEST_pool_multi_token_test.gnoa
- pool/_TEST_pool_same_token_pair_diff_fee_test.gnoa
- pool/_TEST_pool_single_lp_test.gnoa
- pool/pool_manager.gno
- pool/pool_register.gno
- router/quotation.gno
- router/router_register.gno
- staker/reward_math.gno
to create pool, user(creator) needs to spend 500 GNS
- this 500 GNS will be send to certain wallet address
> GSW-401 feat: spend 500 gns when creating new pool

- pool/_TEST_math_logic_test.gnoa
- pool/_TEST_pool_multi_lp_fee_api_test.gnoa
- pool/_TEST_pool_multi_lp_fee_test.gnoa
- pool/_TEST_pool_multi_lp_test.gnoa
- pool/_TEST_pool_multi_token_test.gnoa
- pool/_TEST_pool_native_swap_test.gnoa
- pool/_TEST_pool_same_token_pair_diff_fee_test.gnoa
- pool/_TEST_pool_single_lp_test.gno
- pool/pool.gno
- pool/pool_manager.gno
- position/_TEST_position_api_test.gnoa
- position/_TEST_position_test.gno
- position/position.gno
- router/_TEST_router_single_path_swap_test.gno
- when creating pool, price and tick should be chosen by token_pair
- fix position.mint condition
> GSW-559: fix pool create pools price depends on input token pair

- _test/gs_test.gno
- _test/phase_v2.mk
- gov/api.gno
- gov/gov_parameters.gno
- gov/proposal_mint.gno
- router/_RPC_api.gno
- router/_RPC_call.gno
- router/_TEST_router_api_getter_test.gno
- router/_TEST_router_dynamic_swap_test.gnoa
- router/_TEST_router_multi_path_dry_test.gnoa
- router/_TEST_router_multi_path_swap_test.gnoa
- router/_TEST_router_single_path_dry_test.gnoa
- router/_TEST_router_single_path_swap_test.gno
- router/quotation.gno
- router/router.gno
- router/swap_inner.gno
- router/swap_multi.gno
- router/swap_single.gno
- staker/_TEST_staker_one_external_test.gno
- if swap type is EXACT_IN, router checks minimum output amount
- if swap type is EXACT_OUT, router checks maximum input amount
> GSW-561 fix: router check minimum output or maximum input

- _setup/fred/fred_test.gno
- _setup/fred/gno.mod
- _setup/fred/thud.gno
- _setup/thud/gno.mod
- _setup/thud/thud.gno
- _setup/thud/thud_test.gno
- _test/init_only.mk
- add 2 grc20 tokens
- this should be NOT registered to contract nor gno-token resource github
> GSW-627 chore: add 2 non register grc20 tokens

- _test/_TEST_init_only_test.gno
- _test/init_only.mk
- when creating pool, use tick(ratio) with grc20 decimal consideration
> GSW-644 chore: use tick with grc20 decimal consideration

- README.md
> fix missing router in testing

- staker/_TEST_staker_collect_reward_test.gno
- staker/_TEST_staker_one_increase_external_test.gnoa
- staker/staker.gno
- collect staking reward without unstaking
> GSW-603 feat: CollectReward()

- position/position.gno
- position/type.gno
- remove token0, token1 limit value
> GSW-679 fix: position liquidity

- position/position.gno
- position/util.gno
- when position is staked, owner(≈user) can not decrease liquidity
> GSW-685 fix: cannot decrease liquidity at staked position

- staker/_RPC_api_incentive.gno
- staker/_RPC_api_stake.gno
- staker/_TEST_staker_collect_reward_test.gnoa
- staker/_TEST_staker_one_external_native_test.gnoa
- staker/_TEST_staker_one_external_test.gnoa
- staker/_TEST_staker_one_increase_external_test.gno
- staker/staker.gno
> GSW-687 feat: staker contract data getter

- _setup/bar/bar.gno
- _setup/baz/baz.gno
- _setup/foo/foo.gno
- _setup/fred/fred.gno
- _setup/gns/gns.gno
- _setup/obl/obl.gno
- _setup/qux/qux.gno
- _setup/st1/st1.gno
- _setup/st2/st2.gno
- _setup/st3/st3.gno
- _setup/st4/st4.gno
- _setup/st5/st5.gno
- _setup/testtokena/testtokena.gno
- _setup/testtokenb/testtokenb.gno
- _setup/testtokenc/testtokenc.gno
- _setup/thud/thud.gno
- _test/_TEST_router_native_wrap_unwrap_test.gno
- _test/live_test.mk
- pool/_TEST_init_test.gno
- position/_TEST_init_test.gno
- position/_TEST_position_test.gno
- router/_TEST_init_test.gno
- staker/_TEST_init_test.gno
- staker/liquidity_amounts.gno
- staker/staker.gno
- Instead of default test accounts, use different address as admin
> GSW-669 feat: use new admin address

- _test/init_only.mk
- _test/live_test.mk
- chain takes about 5 seconds to start, wait for it
> fix: makefile to wait chain

- _test/_TEST_scenario_01_test.gno
- _test/gno.mod
- _test/swap_scenario.gno
- staker/_RPC_api_stake.gno
- staker/reward_math.gno
- staker/staker.gno
- only subtract already claimed value when CollectReward() called, not APIReward()
- bug was discovered by @jinoosss
> GSW-712 fix: staker reward calculation

- _test/_TEST_helper_test.gno
- _test/_TEST_scenario_02_test.gnoa
- _test/_TEST_scenario_03_test.gnoa
- _test/_TEST_scenario_04_test.gnoa
- position/liquidity_management.gno
- fix rounding error when calculation
> GSW-719 fix: tick rouding error

- _test/init_only.mk
1. deploy test faucet realm when chain is being initialized
> fix: deploy faucet realm

- router/router.gno
1. fix swap amount calculation
> GSW-733 fix: amountSpecified is zero

- pool/_RPC_call.gno
- pool/tick_math.gno
- `MakeRpcPools` will return all of pool's detail data from on chain
- return condition of tick_math
> GSW-810 feat: `MakeRpcPools` to return list of pools data

- router/_RPC_api.gno
- formula was returning `div by 0` when tick is too low
> GSW-820 fix: token price calculation

- pool/_RPC_call.gno
- `pool` contract `MakeRpcPool(s)` to return position info
> GSW-835 feat: `MakeRpcPool(s)` to return position info

- router/_RPC_api.gno
- router/_TEST_router_api_getter_test.gno
- use common json struct with key&value named, for router api function
> GSW-838 feat add query metadata in every api function #2

- staker/_RPC_api_incentive.gno
> GSW-838 feat add query metadata in every api function #3

- consts/consts.gno
- pool/_RPC_dry.gno
- pool/bit_math.gno
- pool/emergency_halt.gno
- pool/gno_helper.gno
- pool/pool.gno
- pool/pool_register.gno
- pool/position.gno
- pool/sqrt_price_math.gno
- pool/tick.gno
- pool/tick_bitmap.gno
- pool/tick_math.gno
- pool/utils.gno
- all of fixed values are defined at consts(it can be realm or package)
- all of const values in `pool` contract are replaced
> const values in other contracts will be removed
> GSW-851 feat: use fixed-value from const

- pool/_RPC_api.gno
- pool/_RPC_dry.gno
- pool/bit_math.gno
- pool/emergency_halt.gno
- pool/pool.gno
- pool/pool_manager.gno
- pool/pool_register.gno
- pool/position.gno
- pool/sqrt_price_math.gno
- pool/tick.gno
- pool/tick_bitmap.gno
- pool/tick_math.gno
- position/_RPC_api.gno
- position/liquidity_management.gno
- position/position.gno
- router/_RPC_api.gno
- staker/staker.gno
- mutex lock pattern has been applied when calling transfer or transferFrom function to prevent reentrancy attack (just in case)
- `poolKey` -> `poolPath`
- `tokenA` -> `token0`
- `tokenB` -> `token1`
> GSW-856 feat: mutex lock

- consts/consts.gno
- pool/_GET_pool.gno
- pool/_RPC_dry.gno
- pool/bit_math.gno
- pool/emergency_halt.gno
- pool/liquidity_math.gno
- pool/pool.gno
- pool/pool_manager.gno
- pool/pool_register.gno
- pool/position.gno
- pool/swap_math.gno
- pool/swap_parameters.gno
- pool/tick.gno
- pool/tick_bitmap.gno
- pool/tick_math.gno
- pool/utils.gno
> GSW-859 chore: better require handling

- pool/_TEST_math_logic_test.gnoa
- pool/_TEST_pool_multi_token_test.gnoa
- pool/_TEST_pool_native_swap_test.gnoa
- pool/_TEST_pool_single_lp_test.gnoa
add miised const package in pool
> Add consts package and update references to MIN_PRICE

- _test/_TEST_scenario_01_full_happy_case_test.gno
- _test/_TEST_scenario_03_FAIL_liquidity_test.gnoa
- _test/_TEST_scenario_04_router_one_route_one_hop_test.gnoa
- _test/_TEST_scenario_05_router_one_route_two_hop_test.gnoa
- _test/_TEST_scenario_98_router_only_upper_position_println_test.gnoa
- _test/init_only.mk
- _test/live_test.mk
1. makefile to handle consts realm
2. testcase to obsolete api functions
> GSW-860 fix makefile testcases

- pool/bit_math.gno
Extracted the common patterns into a struct (`bitShift`) and modified it to process the values in a loop.
> refactor: pool/bit_math

- pool/_TEST_INIT_register_tokens_test.gno
- pool/pool_register.gno
- position/_TEST_INIT_register_tokens_test.gno
- position/_TEST_position_test.gnoa
- position/_TEST_position_test_two_position_used_single_swap_test.gno
- position/position.gno
- router/_TEST_INIT_register_tokens_test.gno
- router/router_register.gno
- staker/_TEST_INIT_register_tokens_test.gno
- staker/staker_register.gno
1. listing registered grc20 tokens in `pool`, `router`, `staker` 
2. behavior of registering grc20 token requires privileges
3. `position.CollectFee` was returning 0
wait for #173 #174 #175 #176 #177
> GSW-876 feat register token helpers

- pool/tick_bitmap_test.gno
Added tests for functions not related to bigint.
> GSW-888: Test for Pool Tick Bitmap

- README.md
- __local/test/gnoswap.txtar
- x/default_token_register/default_token_register.gno
- x/default_token_register/gno.mod
1. register contract to register grc20 tokens that exists in repo by default
- `gno.land/r/demo/foo20`
- `gno.land/r/demo/wugnot`
> GSW-1003 feat: register contract for default grc20 tokens (foo20,wugnot)

- position/_RPC_api.gno
> hotfix: position api unclaimed fee calculation

- router/_RPC_api.gno
- router/_TEST_/_TEST_router_ratio_test.gn
1. depends on pool's current tick, calculation may results overflow
> GSW-1025 fix: overflow router ratio calculation

- __local/grc20_tokens/qux/qux.gno
- __local/grc20_tokens/usdc/usdc.gno
> chore: remove faucet and mint

- position/_RPC_api.gno
- position/_TEST_/__TEST_position_api_test.gnoA
1. entire(or single) position unclaimed fee getter
> feat: entire(or single) position unclaimed fee getter

- __local/test/test_data.mk
- staker/_RPC_api_incentive.gno
> hotfix: remove unused variable

- position/_TEST_/__TEST_position_reposition_gnot_pair_test.gnoA
- position/_TEST_/__TEST_position_reposition_grc20_pair_test.gnoA
- position/position.gno
- staker/_RPC_api_incentive.gno
- staker/_TEST_/__TEST_staker_rpc_api_test.gnoA
1. re-range existing position without minting new position but use old one.
> feat: reposition with same lp token id

- __local/test/test_data.mk
- position/position.gno
- router/_TEST_/__TEST_0_INIT_VARS_HELPERS_test.gno
- router/_TEST_/__TEST_router_swap_route_1route_1hop_native_in_out_test.gnoA
- router/router.gno
1. if `wugnot` is token out, collect 0.15% fee in `ugnot`
> GSW-1140 fix: collect swap router fee in ugnot if wugnot is token out

- __local/test/test_data.mk
- position/_TEST_/__TEST_position_increase_burned_position_test.gnoA
- position/position.gno
- staker/_RPC_api_stake.gno
- staker/reward_math.gno
1. burned position's liquidity can be increase.
this pr kinda reverts previous one #244
> GSW-1198 feat burned positions liquidity can be increased

- __local/grc20_tokens/bar/bar.gno
- __local/grc20_tokens/bar/gno.mod
- __local/grc20_tokens/baz/baz.gno
- __local/grc20_tokens/baz/gno.mod
- __local/grc20_tokens/foo/foo.gno
- __local/grc20_tokens/foo/gno.mod
- __local/grc20_tokens/obl/gno.mod
- __local/grc20_tokens/obl/obl.gno
- __local/grc20_tokens/qux/gno.mod
- __local/grc20_tokens/qux/qux.gno
- __local/grc20_tokens/usdc/gno.mod
- __local/grc20_tokens/usdc/usdc.gno
- __local/test/test_data.mk
- _deploy/r/demo/gns/gno.mod
- _deploy/r/demo/gns/gns.gno
- router/_TEST_/__TEST_router_swap_route_1route_1hop_native_in_out_test.gnoA
- router/protocol_fee_swap.gno
- staker/calculate_pool_position_reward.gno
1. grc20 tokens // https://github.com/gnolang/gno/pull/2529
2. remove unused var 
3. give router swap protocol fee to protocol_fee contract
current contract deployment tested with https://github.com/gnoswap-labs/gno/commit/8ddf0d833f143e87a5520adb1a90ee705f7e471f
> GSW-1251 refactor: grc20 tokens

- staker/_TEST_/__TEST_staker_external_short_warmup_period_test.gno
- staker/calculate_pool_position_reward.gno
- staker/reward_math.gno
- staker/staker.gno
1. decrease warm up period duration
2. start external incentive after 2 minute
works with https://github.com/gnolang/gno/commit/f980fd6a07e8e6b4fd05ac484c0d140354ba8327
> GSW-714 test: decrease warm up period time, start external incentive after 2 minute

- __local/grc20_tokens/register_gnodev/register_gnodev.gno
- community_pool/community_pool.gno
- community_pool/token_register.gno
1. community_pool can have various grc20 tokens, therefore it should support register pattern
> GSW-1260 feat: community pool to support register pattern

- staker/_GET_no_receiver.gno
- staker/_RPC_api_incentive.gno
- staker/__TEST_staker_short_warmup_period_internal_01_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_02_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_03_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_04_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_05_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_06_test.gno
- staker/calculate_pool_position_reward.gno
- staker/manage_pool_tiers.gno
- staker/reward_math.gno
- staker/staker.gno
- staker/type.gno
1. internal(gns block emission) getter to include timestamp
> GSW-1269 feat: internal incentive getter to include timestamp

- __local/test/test_data.mk
- router/protocol_fee_swap.gno
- staker/protocol_fee_unstaking.gno
1. unstaking fee should be 1%(bps: 100) by default
> hotfix: unstaking protocol fee to 1%

- _deploy/r/gnoswap/gns/gns.gno
- _deploy/r/gnoswap/gns/halving.gno
- emission/distribution.gno
- emission/emission.gno
- staker/_GET_no_receiver.gno
- staker/_RPC_api_stake.gno
- staker/__TEST_staker_short_warmup_period_external_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_02_test.gnoA
- staker/__TEST_staker_short_warmup_period_internal_03_test.gno
- staker/calculate_pool_position_reward.gno
- staker/protocol_fee_unstaking.gno
- staker/reward_math.gno
- staker/staker.gno
1. calculate position gns emissino amount for each warm up period
2. chore getter
lots of debugging message included in this pr, it's for qa debugging.
after qa finish, it will be removed
> GSW-1283 fix calculate position gns emission amount for each warm up period

- staker/calculate_pool_position_reward.gno
- staker/reward_math.gno
1. to calculate how much left for each pool in each block, left variable needs to  `ADD` how much has been calculate for each position in each pool
> hotfix: pool left amount calculation

- staker/staker.gno
1. lp token can be staked even external incentive hasn't started yet.
> GSW-1319 fix: unable to stake before the staking period starts

- position/position.gno
- position/tests/__TEST_position_reposition_gnot_pair_test.gnoA
- position/tests/__TEST_position_reposition_grc20_pair_test.gnoA
1. support slippage for repositioning (just like minting)
> GSW-1331 feat: support slippage for repositioning

- setup.py
Create python CLI tool for initial setup
```bash
python setup_gnoswap.py /path/to/your/workdir
```
> setup script

- README.md
- setup.py
- Create repo cloning option
- Set default work directory
- Auto detect directory position by using `gno.mod` content
- Update readme
> feat: Update setup.py

- pool/liquidity_math.gno
- pool/pool.gno
- pool/pool_manager.gno
- pool/position.gno
- pool/position_modify.gno
- pool/position_update.gno
- pool/protocol_fee_pool_creation.gno
- pool/protocol_fee_withdrawal.gno
- pool/tick.gno
- pool/tick_bitmap.gno
- pool/token_register.gno
> Update pool documents and Some Refactoring

- position/_RPC_dry.gno
- position/position.gno
- position/tests/__TEST_RPC_dry_test.gnoA
- position/type.gno
- Update docs for public functions
- Refactored functions that were detected by complexity checks.
> Update Position docs and Apply Refactoring

- staker/_GET_no_receiver.gno
- staker/_RPC_api_stake.gno
- staker/calculate_pool_position_reward.gno
- staker/external_token_list.gno
- staker/manage_pool_tiers.gno
- staker/mint_stake.gno
- staker/staker.gno
- staker/token_register.gno
- staker/wrap_unwrap.gno
> Update Staker's documents

- pool/position_update.gno
- pool/tick_bitmap.gno
- position/position.gno
- position/type.gno
> remove new instance (Position)

- README.md
- setup.py
> GSW-1419 docs: readme

- _deploy/r/gnoswap/gns/halving.gno
1. add event for `SetAvgBlockTimeInMs`
related PR #305
> GSW-1379 feat: add event for SetAvgBlockTimeInMs

- pool/liquidity_math.gno
- router/router.gno
- router/tests/__TEST_router_swap_route_1route_1hop_all_liquidity_exact_in_test.gnoA
- router/tests/__TEST_router_swap_route_1route_1hop_all_liquidity_exact_out_test.gnoA
- router/tests/__TEST_router_swap_route_1route_1hop_out_range_test.gnoA
1. router to check output amount for EXACT_OUT swap
> so user can actually get requested amount
> GSW-1444 fix: router to check output amount for EXACT_OUT swap

- staker/tests/__TEST_staker_short_warmup_period_external_15_90d_test.gno
- staker/tests/__TEST_staker_short_warmup_period_external_16_180d_test.gnoA
- staker/tests/__TEST_staker_short_warmup_period_external_17_365d_test.gnoA
1. 3 test case for each external incentive duration (90, 180, 365)
- single pool has 4 position
- all positions are in-range
- all positions are staked
- each position has different liquditiy
> GSW-1488 test: each external duration with 4 different staked position

- staker/tests/__TEST_staker_short_warmup_period_internal_external_92_test.gno
1. origin test case for api to compare
> related api testcase pr: https://github.com/gnoswap-labs/gnoswap-api/pull/141
> GSW-1537 test // test case with mock-data

- gov/governance/_RPC_api_proposal.gno
- gov/governance/config.gno
- gov/governance/governance_proposal.gno
- gov/governance/tests/__TEST_0_INIT_VARIABLE_AND_HELPER_test.gno
- gov/governance/tests/__TEST_governance_proposal_community_pool_spend_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_execute_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_text_test.gnoA
- gov/governance/type.gno
- gov/governance/util.gno
- gov/staker/_RPC_api_history.gno
- gov/staker/_RPC_api_staker.gno
- gov/staker/delegate_undelegate.gno
- gov/staker/staker.gno
- gov/staker/tests/__TEST_staker_02_emission_reward_test.gnoA
- gov/staker/tests/__TEST_staker_03_protocol_fee_test.gnoA
- gov/staker/util.gno
1. proposal quorum should be 50% of xgns total supply at the time of its creation
2. add orig caller, prevRealm in event to to emit
3. to create proposal, proposer needs to have at least 1_000 xGNS (1_000_000_000u)
4. testcase
5. undelegation should decrease amount from very first
> GSW-1575 feat: proposal quorum

- gov/governance/governance_proposal.gno
- gov/governance/tests/__TEST_governance_proposal_text_test.gnoA
1. add proposal check condition
- if no activity requested during voting period time for certain proposal, it needs to be updated
> GSW-1577 fix: condition to check proposal status

- gov/governance/governance_proposal.gno
- gov/governance/tests/__TEST_governance_proposal_community_pool_spend_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_execute_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_text_test.gnoA
1. same address can propose several proposals
> GSW-1579 feat: proposer can propose several proposals

- gov/governance/tests/__TEST_governance_vote_with_only_delegated_test.gno
- gov/staker/_RPC_api_history.gno
- gov/staker/delegate_undelegate.gno
- gov/staker/history.gno
- gov/staker/staker.gno
- gov/staker/tests/__TEST_api_test.gnoA
1. to calculate actual voting weight, contract needs use `ModifiedDelegationHistory` for delegated address, not delegator address
> GSW-1604 fix: wrong voting weight

- __local/grc20_tokens/g1er355fkjksqpdtwmhf5penwa82p0rhqxkkyhk5/register_gnodev/register_gnodev.gno
- gov/staker/_RPC_api_staker.gno
- protocol_fee/protocol_fee.gno
1. register grc20 tokens to gov/staker to calculate pf rewards
> GSW-1618 fix: gov staker protocol fee reward calculation

- launchpad/launchpad_deposit.gno
- launchpad/tests/__TEST_launchpad_tier180_single_deposit_reward_by_proejct_tier_test.gnoA
- launchpad/tests/__TEST_launchpad_two_project_two_tier_two_deposit_collect_gns_test.gnoA
1. collecting deposited gns (after deposit project's tier's is over)
> should be done by not entire deposit, but also each project and single deposit
> GSW-1662 feat able to collect deposit gns by project and each single deposit

- __local/test/launchpad_test.mk
- launchpad/launchpad_deposit.gno
- launchpad/launchpad_init.gno
- Need to exception logic to check xGNS in launchpad
> GSW-1677 hotfix: need to exception logic to check xGNS 

- launchpad/launchpad_deposit.gno
- launchpad/launchpad_init.gno
- launchpad/launchpad_reward.gno
- launchpad/tests/__TEST_launchpad_create_project_test.gnoA
- launchpad/type.gno
1. each project's pool reward should be (calculated and) distributed if it has at least one deposit
> GSW-1697 feat: distribute project pool reward if it has at least one deposit

- community_pool/token_register.gno
- gov/staker/token_register.gno
- launchpad/token_register.gno
- pool/token_register.gno
- protocol_fee/token_register.gno
- router/token_register.gno
- staker/token_register.gno
1. allow realm made by grc20-register can register token
> hotifx: allow grc20-register to register token

- gov/governance/config.gno
- gov/governance/governance_proposal.gno
- gov/governance/tests/__TEST_governance_proposal_MULTI_execute_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_community_pool_spend_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_execute_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_status_update_test.gnoA
- gov/governance/tests/__TEST_governance_proposal_text_test.gnoA
- gov/governance/tests/__TEST_governance_vote_with_only_delegated_test.gnoA
- gov/governance/tests/__TEST_governance_vote_without_launchpad_xgns_test.gnoA
- gov/staker/staker.gno
- gov/staker/tests/__TEST_api_test.gnoA
- launchpad/consts.gno
- launchpad/launchpad_deposit.gno
1. removed value for testing with testcase and on-chain tests.
> each testcase overwrites from testing logic
> on-chain test value will be overwrite when we actually deploy those.
> refactor: remove test value

- launchpad/launchpad_reward.gno
1. emit event with necessary data before updating it.
> fix: emit event before updating value

- launchpad/_RPC_api_deposit.gno
- launchpad/_RPC_api_project.gno
- launchpad/launchpad_init.gno
- launchpad/launchpad_reward.gno
- launchpad/tests/__TEST_RPC_api_test.gnoA
- launchpad/tests/__TEST_launchpad_create_project_test.gnoA
- launchpad/tests/__TEST_launchpad_deposit_project_single_recipient_test.gnoA
- launchpad/tests/__TEST_launchpad_deposit_project_two_recipient_test.gnoA
- launchpad/tests/__TEST_launchpad_refund_ended_proejct_no_deposit_test.gnoA
- launchpad/tests/__TEST_launchpad_refund_ended_proejct_with_tier30_test.gnoA
- launchpad/tests/__TEST_launchpad_tier180_single_deposit_reward_by_proejct_tier_test.gnoA
- launchpad/tests/__TEST_launchpad_tier30_single_deposit_01_deposit_collect_gns_test.gnoA
- launchpad/tests/__TEST_launchpad_tier30_single_deposit_02_deposit_reward_by_proejct_test.gnoA
- launchpad/tests/__TEST_launchpad_tier30_single_deposit_03_deposit_reward_by_deposit_test.gnoA
- launchpad/tests/__TEST_launchpad_tier30_single_deposit_04_deposit_reward_by_deposit_endheight_test.gnoA
- launchpad/tests/__TEST_launchpad_tier30_two_deposit_reward_by_project_test.gnoA
- launchpad/tests/__TEST_launchpad_tier90_single_deposit_reward_by_proejct_tier_test.gnoA
- launchpad/tests/__TEST_launchpad_two_project_two_tier_two_deposit_collect_gns_test.gnoA
- launchpad/type.gno
1. admin can trigger function that transfers left amount from ended project to certain address
> GSW-1713-feat-transfer-left-amount-from-ended-project-by-admin

- .github/workflows/release.yml
- changelog.md
Add `changelog.md` files and action for automation
> feat: Add `changelog.md` file

- _deploy/r/gnoswap/gnft/gnft.gno
- _deploy/r/gnoswap/gnft/tests/gnft_test.gno
1. follow IGRC721Metadata spec for gnoswap nft
> GSW-1798 feat: follow `IGRC721Metadata` spec

- pool/pool_manager.gno
- staker/calculate_pool_position_reward.gno
1. emit pool's `sqrtPriceX96` when created
2. removed unused variables
> GSW-1885/feat-emit-pool-price-when-created

- position/position.gno
1. emit position.Mint function parameter to idenfiiy liquidity provider
2. position operator update method
> GSW-1909 feat: emit position.Mint parameter

- staker/reward_internal_emission.gno
- staker/reward_recipient_store.gno
- staker/staker.gno
- After unstake token, liquidity pointer become nil issue
- Fix this bug to copy value to calculation and then set result
> GSW-1959 fix: liquidity pointer nil bug after unstake

- _deploy/p/gnoswap/int256/cmp.gno
- _deploy/p/gnoswap/int256/cmp_test.gno
Added `nil` check when comparing two `int256` values
> chore(int256): Prevent Passing `nil` Value When Compare Values

- pool/errors.gno
- pool/pool.gno
- Fix typos
- Add comments to support understanding error code
> GSW-1838 refactor: added comments for details and fix typo

- pool/errors.gno
- pool/liquidity_math.gno
- pool/liquidity_math_test.gno
- Added comments to understanding
- Modified to check input parameter validation
- Added test code
> GSW-1838 refactor: pool contract liquidity math

- protocol_fee/token_register.gno
- router/token_register.gno
- staker/token_register.gno
- staker/warm_up.gno
SatisfyCondition -> SatisfyCond
> fix: wrong function name

- __local/grc20_tokens/onbloc/bar/bar.gno
- __local/grc20_tokens/onbloc/baz/baz.gno
- __local/grc20_tokens/onbloc/foo/foo.gno
- __local/grc20_tokens/onbloc/obl/obl.gno
- __local/grc20_tokens/onbloc/qux/qux.gno
- __local/grc20_tokens/onbloc/usdc/usdc.gno
- _deploy/r/gnoswap/common/access.gno
- _deploy/r/gnoswap/gns/gns.gno
- setup.py
unable to run the Gnoswap test on local env due to a type error, so I fixed it.
updated the token files to align with the latest GRC20 specification.
> GSW-1699 feat: Update Tokens to Follow New GRC20 Specs

- pool/protocol_fee_pool_creation.gno
- pool/protocol_fee_pool_creation_test.gno
- change from err to string type error when panic
- added test code for protocol_fee_pool_creation.gno
- rename from prevRealm to prevPkgPath to more clear
> GSW-1838 refactor: protocol fee creation

- __local/test/launchpad_test.mk
- pool/_GET_receiver.gno
- pool/_RPC_api.gno
- pool/pool.gno
- pool/pool_manager.gno
- pool/position.gno
- pool/type.gno
1. change pool.position type from `map` to `avl`
> currently, facing issue when map has pointer value
> GSW-1981 hotfix: change pool.position type from map to avl

- _deploy/r/gnoswap/gns/gns.gno
Declared a type but not updating the value. fixed
> fix: gns token

- pool/api.gno
- pool/api_test.gno
> refactor: pool's api

- pool/errors.gno
- pool/utils.gno
- pool/utils_test.gno
1. remove unused function
2. add test case for each function
> GSW-1838 refactor: utils

- position/__TEST_0_INIT_TOKEN_REGISTER_test.gno
- position/__TEST_0_INIT_VARS_HELPERS_test.gno
- position/_helper_test.gno
1. helper to reset position state
> GSW-1839 helper to reset position's state

- .gitignore
- sonar-project.properties
- exclusion test code
- ignore related with sonar local test file
> chore: update sonar option

- setup.py
Modified the setup script to reflect the new file structure.
While previously directories were recognized using hardcoded values, it has now been modified to fully recognize and process paths specified in gno.mod.
> feat: Update setup script

- tests/integration/testdata/public_tx.txtar
Test more functions with txtar testing
> test: test more function txtar testing

- contract/r/gnoswap/gov/governance/tests/governance_proposal_MULTI_execute_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_proposal_community_pool_spend_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_proposal_execute_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_proposal_status_update_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_proposal_text_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_vote_gov_delegated_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_vote_gov_delegated_undelegated_after_propose_before_vote_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_vote_gov_delegated_undelegated_before_propose_test.gnoA
- contract/r/gnoswap/gov/governance/tests/governance_vote_with_launchpad_xgns_test.gnoA
- contract/r/gnoswap/gov/staker/staker.gno
- contract/r/gnoswap/gov/staker/staker_test.gno
- contract/r/gnoswap/gov/staker/tests/api_test.gnoA
- contract/r/gnoswap/gov/staker/tests/emission_gns_mint_test.gnoA
- contract/r/gnoswap/gov/staker/tests/governance_reward_emission_test.gnoA
- contract/r/gnoswap/gov/staker/tests/governance_reward_protocol_fee_test.gnoA
- contract/r/gnoswap/gov/staker/tests/governance_reward_protocol_fee_with_launchpad_test.gnoA
- contract/r/gnoswap/launchpad/tests/launchpad_create_project_test.gnoA
- contract/r/gnoswap/launchpad/tests/launchpad_reward_and_gov_reward_01_test.gnoA
- contract/r/gnoswap/launchpad/tests/launchpad_reward_and_gov_reward_02_test.gnoA
- contract/r/gnoswap/launchpad/tests/launchpad_reward_and_gov_reward_03_test.gnoA
- tests/test.mk
Apply referral system to gov/staker's Delegate function
Changes:
The parameter of the gov/staker's `Delegate` function was changed to accept `std.Address`.
> feat(r/gov/staker): Add referral to gov/staker `Delegate` function

- contract/p/gnoswap/halt/common.gno
- contract/p/gnoswap/halt/doc.gno
- contract/p/gnoswap/halt/gno.mod
- contract/p/gnoswap/halt/halt.gno
- contract/p/gnoswap/halt/level.gno
- contract/p/gnoswap/halt/level_test.gno
- contract/p/gnoswap/halt/logger.gno
- contract/p/gnoswap/halt/mamanger.gno
- contract/p/gnoswap/halt/manager_test.gno
> feat: Halt Protocol

- Makefile
> chore: fmt command

- contract/p/gnoswap/rbac/README.md
Added README to the rbac package.
> doc(p/rbac): Add Readme

- contract/r/gnoswap/halt/README.md
- contract/r/gnoswap/halt/gno.mod
- contract/r/gnoswap/halt/halt.gno
- contract/r/gnoswap/halt/halt_test.gno
- contract/r/gnoswap/halt/utils.gno
> feat(r/halt): Realm-level halt system

- contract/r/gnoswap/common/liquidity_amounts.gno
- contract/r/gnoswap/gov/staker/tests/emission_gns_mint_test.gnoA
- contract/r/gnoswap/pool/position.gno
- contract/r/gnoswap/pool/tick.gno
- contract/r/gnoswap/pool/type.gno
- contract/r/gnoswap/position/position_mint_test.gno
- contract/r/gnoswap/position/tests/position_native_increase_decrease_test.gnoA
- contract/r/gnoswap/position/tests/position_tokens_owed_left_pair_more_action_exact_test.gnoA
- contract/r/gnoswap/staker/reward_calculation_canonical_test.gno
- contract/r/gnoswap/staker/tests/full_internal_external_test.gnoA
- contract/r/gnoswap/staker/tests/staker_short_warmup_period_internal_01_test.gnoA
- removed unnecessary print logs
- update invalid function usages in comments
> chore: Remove Unnecessary Print Logs

- contract/r/gnoswap/router/exact_in_test.gno
- contract/r/gnoswap/router/swap_inner_test.gno
- contract/r/gnoswap/router/swap_multi_test.gno
- contract/r/gnoswap/router/swap_single_test.gno
- contract/r/gnoswap/router/utils_test.gno
> refactor: use access contract in router

- contract/r/gnoswap/gov/staker/reward.gno
- contract/r/gnoswap/protocol_fee/protocol_fee.gno
When delegate to gov staker multiple time, delegation is failed with log that is "uninitialized map index"
> fix: delegate fail issue

- contract/r/gnoswap/router/_helper_test.gno
- contract/r/gnoswap/router/exact_out_test.gno
- contract/r/gnoswap/router/swap_inner.gno
- contract/r/gnoswap/router/swap_inner_test.gno
- Added defensive code to address missing overflow checks in the router contract
- Included test cases that reproduce the overflow issue in dryswap at specific threshold values
> fix, test: DrySwap Overflow Checks

- contract/r/gnoswap/pool/pool_type.gno
- Fixes an error where only one tick is output.
- Fixes incorrectly using Tick Iterator syntax.
> fix: fix a tick iterator

- contract/r/gnoswap/community_pool/community_pool.gno
- contract/r/gnoswap/community_pool/community_pool_test.gno
- contract/r/gnoswap/emission/_helper_test.gno
- contract/r/gnoswap/emission/callback.gno
- contract/r/gnoswap/emission/distribution.gno
- contract/r/gnoswap/emission/distribution_test.gno
- contract/r/gnoswap/emission/emission.gno
- contract/r/gnoswap/emission/emission_test.gno
- contract/r/gnoswap/emission/utils.gno
- contract/r/gnoswap/gov/xgns/xgns.gno
- contract/r/gnoswap/gov/xgns/xgns_test.gno
- community_pool
- emission
- gov/xgns
Note: The commented test appears to be a poorly constructed test and will need to be fixed.
> apply interrealm take3

- contract/p/gnoswap/uint256/conversion.gno
- contract/r/gnoswap/pool/_helper_test.gno
- contract/r/gnoswap/pool/pool.gno
- contract/r/gnoswap/pool/pool_manager.gno
- contract/r/gnoswap/pool/pool_test.gno
- contract/r/gnoswap/pool/pool_transfer.gno
- contract/r/gnoswap/pool/pool_transfer_test.gno
- contract/r/gnoswap/pool/protocol_fee.gno
- contract/r/gnoswap/pool/protocol_fee_test.gno
- contract/r/gnoswap/pool/swap_test.gno
- contract/r/gnoswap/pool/utils.gno
- contract/r/gnoswap/position/native_token.gno
- contract/r/gnoswap/position/position.gno
- contract/r/gnoswap/position/position_mint.gno
- contract/r/gnoswap/position/type.gno
- contract/r/gnoswap/protocol_fee/api_test.gno
- contract/r/gnoswap/protocol_fee/protocol_fee.gno
- contract/r/gnoswap/protocol_fee/protocol_fee_test.gno
- contract/r/gnoswap/router/_helper_test.gno
- contract/r/gnoswap/router/base.gno
- contract/r/gnoswap/router/protocol_fee_swap.gno
- contract/r/gnoswap/router/router.gno
- contract/r/gnoswap/router/swap_inner.gno
- contract/r/gnoswap/router/utils.gno
- contract/r/gnoswap/router/wrap_unwrap.gno
- contract/r/gnoswap/staker/getter.gno
- contract/r/gnoswap/staker/protocol_fee_unstaking.gno
- protocol_fee
- fix some type errors in main contracts
> interrealm take 4

- contract/r/gnoswap/rbac/manager_test.gno
This PR adds comprehensive test coverage for RBAC (Role-Based Access Control) functionality at the realm level. The tests cover all major RBAC operations including role registration, permission management, and access control validation.
- **`TestRegisterRole`**: Tests role registration with success/failure scenarios
- **`TestRegisterPermission`**: Tests permission registration for roles
- **`TestCheckPermission`**: Tests permission validation for different callers
- **`TestUpdatePermission`**: Tests permission checker updates
- **`TestRemovePermission`**: Tests permission removal functionality
- **`TestRemoveRole`**: Tests role deletion with authorization checks
- **`TestDeclareRole`**: Tests declarative role creation with permissions
- Admin-only operations validation
- Unauthorized …
> feat(test): rbac realm tests

- contract/r/gnoswap/protocol_fee/api_test.gno
This PR refactors the protocol fee API tests to use table-driven test patterns, improving test maintainability and coverage. The changes convert existing linear test cases into structured test tables with clear setup, execution, and verification phases.
**Before:**
```go
func TestApiGetAccuTransferToGovStaker(t *testing.T) {
addAccuToGovStaker("gno.land/r/onbloc/bar", 1000)
addAccuToGovStaker("gno.land/r/onbloc/qux", 2000)
result := ApiGetAccuTransferToGovStaker()
uassert.Equal(t, `{"height":"123","now":"1234567890","gno.land/r/onbloc/bar":"1000","gno.land/r/onbloc/qux":"2000"}`, result)
// ... more test logic
}
```
**After:**
```go
func TestApiGetAccuTransferToGovStaker(t *testing.T) {
tests := []struct {
name                string
historyItem         []struct {
token  string
amount …
```
> feat(test): protocol fee realm api tests

- contract/r/gnoswap/staker/external_deposit_fee_test.gno
- contract/r/gnoswap/staker/external_token_list.gno
- contract/r/gnoswap/staker/external_token_list_test.gno
This PR introduces comprehensive test improvements for the staker realm, focusing on enhanced test structure, better error handling validation, and improved code organization.
- **Replaced manual panic/abort handling** with standardized `uassert` utilities for consistent test behavior
- **Added structured test cases** with clear expected outcomes for both success and failure scenarios
- **Implemented Given-When-Then pattern** for better test readability and maintainability
- **Added comprehensive permission validation tests** for admin and governance functions
- **Enhanced error message validation** to ensure proper authorization error handling
- **Implemented test utility functions** for setting up permission scenarios:
- `setupExternalDepositFeeAdminPermission()`
- …
> feat(test): staker realm tests

- contract/r/gnoswap/staker/reward_calculation_pool.gno
- contract/r/gnoswap/staker/reward_calculation_warmup.gno
Added a guard to areas where division by zero errors could potentially occur.
> fix(staker): Add division by zero guards

- contract/r/gnoswap/launchpad/launchpad_deposit_gns_test.gno
- contract/r/gnoswap/launchpad/launchpad_reward_test.gno
- contract/r/gnoswap/launchpad/project_test.gno
- contract/r/gnoswap/launchpad/utils.gno
- Newly covered functions
- `collectDepositReward`
- `DepositGns`
- `Project` type related methods
| File Name | Prev (%) | Current (%) |
| --- | --- | --- |
| `launchpad_reward.gno` | 29.7 | 51.6 |
| `launchpad_deposit.gno` | 53.2 | 93.5 |
| `project.gno` | 50.0 | 87.1 |
| Total coverage | 64.6 | 78.9 |
> test(launchpad): Increase launchpad's test coverage

- contract/r/gnoswap/emission/distribution.gno
This PR refactors the leftAmount handling logic in the GNS distribution system by moving responsibility from `distributeToTarget` to `MintAndDistributeGns`, while also removing unreachable dead code that was impossible to execute.
- **Removed unreachable condition**: 
```go
// This code could never be executed
if leftAmount < 0 {
panic(addDetailToError(
errInvalidEmissionTarget,
ufmt.Sprintf("total distributed amount (%d) exceeds original amount (%d)", totalSent, amount),
))
}
```
- **Before**: `distributeToTarget` calculated and managed leftAmount internally
- **After**: `distributeToTarget` only performs distribution and returns total sent amount
- **New approach**: `MintAndDistributeGns` handles leftAmount calculation explicitly
- Eliminated unreachable panic condition that confused …
> feat: improve GNS distribution left amount handling

- contract/r/gnoswap/rbac/manager_extended_test.gno
- tests/scenario/rbac/gnomod.toml
- tests/scenario/rbac/rbac_declarative_creation_filetest.gno
- tests/scenario/rbac/rbac_role_management_filetest.gno
- RBAC system initialization
- Role and permission registration
- Permission checks for various actors
- Permission updates and removals
- System state verification after operations
> test(r/rbac): Add scenario tests and unit tests for rbac module

- contract/r/gnoswap/gov/governance/governance_propose.gno
This PR enhances the error handling and validation logic for proposal creation by improving the `getUserVotingInfoSnapshot` function's return type and centralizing voting weight validation, providing better error messages and more robust validation.
- **Before**: `getUserVotingInfoSnapshot` returned `(map[string]*VotingInfo, int64, bool)`
- **After**: Returns `(map[string]*VotingInfo, int64, error)` for better error handling
```go
// Before: Simple boolean check
if !ok || maxVotingWeight <= 0 {
return votingInfos, maxVotingWeight, false
}
return votingInfos, maxVotingWeight, true
// After: Specific error return
if !ok || maxVotingWeight <= 0 {
return votingInfos, maxVotingWeight, errNotEnoughVotingWeight
}
return votingInfos, maxVotingWeight, nil
```
- **Before**: Validation logic …
> feat: improve voting conditions when creating proposal

- contract/r/gnoswap/launchpad/counter.gno
- contract/r/gnoswap/launchpad/counter_test.gno
- contract/r/gnoswap/launchpad/deposit.gno
- contract/r/gnoswap/launchpad/deposit_test.gno
- contract/r/gnoswap/launchpad/launchpad_deposit.gno
- contract/r/gnoswap/launchpad/launchpad_deposit_gns_test.gno
- contract/r/gnoswap/launchpad/launchpad_deposit_test.gno
- contract/r/gnoswap/launchpad/launchpad_withdraw_test.gno
- contract/r/gnoswap/launchpad/reward_manager_test.gno
- contract/r/gnoswap/launchpad/tier_allocation_test.gno
- contract/r/gnoswap/launchpad/tier_duration_test.gno
- tests/scenario/launchpad/launchpad_deposit_project_multi_recipient_filetest.gno
- tests/scenario/launchpad/launchpad_deposit_project_single_recipient_filetest.gno
This PR refactors the deposit ID generation system to use a global counter-based approach, ensuring truly unique deposit IDs and eliminating potential ID collision issues that could occur with the previous composite ID generation method.
The old system generated deposit IDs by combining multiple parameters:
```go
// Old approach (removed)
func makeDepositID(projectID string, tier int64, depositor std.Address, height int64) string {
return ufmt.Sprintf("%s:%d:%s:%d", projectID, tier, depositor.String(), height)
}
```
- **Risk scenario**: Multiple deposits from the same user, in the same project tier, at the same block height
- **Consequence**: Identical deposit IDs → data corruption and state inconsistency
- **Real impact**: Could lead to deposit overwrites and fund loss
- IDs were long, …
> fix: handle deposit id as unique values

- contract/r/gnoswap/launchpad/launchpad_deposit.gno
- contract/r/gnoswap/launchpad/launchpad_project.gno
- contract/r/gnoswap/launchpad/project.gno
- contract/r/gnoswap/launchpad/project_condition.gno
- contract/r/gnoswap/launchpad/project_condition_test.gno
This PR enhances the project condition validation system by improving error handling, strengthening input validation, and providing more robust condition checking mechanisms for launchpad project creation.
- **Before**: Functions used panic for error conditions
- **After**: Proper error return pattern with graceful error handling
```go
// Before: Panic-based error handling
func CheckConditions(...) {
// conditions check logic
if invalid {
panic("condition failed")
}
}
// After: Error-based handling
func CheckConditions(...) error {
// conditions check logic
if invalid {
return makeErrorWithDetails(errInvalidData, "specific error details")
}
return nil
}
```
- **`CheckCondition`** → **`CheckBalanceCondition`**: More specific method name that clearly indicates balance validation
- …
> feat: improve create project conditions

- contract/r/gnoswap/bridge/register.gno
- contract/r/gnoswap/bridge/register_test.gno
This PR refactors the bridge contract's access control mechanism to dynamically retrieve admin and governance addresses at runtime instead of caching them during initialization, improving system reliability and supporting address updates.
```go
// Before: Static initialization in init()
func init() {
callbackTree = avl.NewTree()
adminAddr, err = access.GetAddress(access.ROLE_ADMIN)  // ❌ May fail if access contract not ready
if err != nil {
panic(err)  // ❌ Contract deployment could fail
}
govAddr, err = access.GetAddress(access.ROLE_GOVERNANCE)
if err != nil {
panic(err)  // ❌ Contract deployment could fail
}
}
```
- **Issue**: Once cached at init time, addresses never update
- **Impact**: If admin/governance addresses change, bridge contract becomes non-functional
- **Risk**: Permanent …
> fix: get a dynamic address for access

- contract/r/gnoswap/access/assert.gno
- Change convert package path method.
- NewCoderealm to DerivePkgAddr
> fix(access): convert package path to address

- tests/deploy.mk
> chore: re-order deploy contracts

- contract/r/gnoswap/gov/staker/assert.gno
- contract/r/gnoswap/gov/staker/assert_test.gno
- contract/r/gnoswap/gov/staker/staker_delegate.gno
- contract/r/gnoswap/gov/staker/staker_delegate_test.gno
- contract/r/gnoswap/gov/staker/staker_delegation_snapshot.gno
- contract/r/gnoswap/gov/staker/staker_reward.gno
Significantly improved the gov/staker contract architecture by enhancing validation mechanisms, removing withdrawal halt dependencies, improving code organization, and optimizing performance.
- **New File**: `contract/r/gnoswap/gov/staker/assert.gno`
- **Extracted Validation Logic**:
```go
// New centralized validation function
func assertIsValidDelegateAmount(amount int64) {
if amount < minimumAmount {
panic(makeErrorWithDetails(errLessThanMinimum, ...))
}
if amount%minimumAmount != 0 {
panic(makeErrorWithDetails(errInvalidAmount, ...))
}
}
```
- **Benefits**: 
- Centralized validation logic
- Consistent error handling
- Easier maintenance and testing
- **Updated Functions**:
- `Delegate()` - Removed `halt.AssertIsNotHaltedWithdraw()`
- `Undelegate()` - Removed …
> feat(gov/staker): improve gov/staker contracts

- contract/r/gnoswap/community_pool/community_pool.gno
- contract/r/gnoswap/community_pool/community_pool_test.gno
Improved the community pool contract by consolidating transfer functions, enhancing authorization flexibility, and implementing better error handling patterns.
- **Removed Duplicate Function**:
```go
// Before: Two separate functions
func TransferTokenByAdmin(cur realm, tokenPath string, to std.Address, amount int64) {
// Admin-only transfer logic
}
func TransferToken(cur realm, tokenPath string, to std.Address, amount int64) {
// Governance-only transfer logic  
}
// After: Single unified function
func TransferToken(cur realm, tokenPath string, to std.Address, amount int64) {
// Both admin and governance can transfer
access.AssertIsAdminOrGovernance(caller)
}
```
- **Flexible Access Control**:
```go
// Before: Separate functions with different permissions
TransferTokenByAdmin() // Admin …
```
> feat(community pool): improve community pool contracts

- contract/r/gnoswap/v1/position/assert.gno
- Update error message of check position owner assertion.
> chore: update error message

- contract/r/gnoswap/v1/staker/getter.gno
- Fix a invalid input parameters.
> fix: invalid input parameters

- contract/r/gnoswap/rbac/README.md
This PR enhances the RBAC documentation by adding comprehensive information about the contract upgrade mechanism used in GnoSwap protocol. 
- Explains how RBAC enables seamless contract upgrades through role address updates
- Details the upgrade process for versioned contracts (e.g., v1 → v2)
- Documents zero-downtime upgrade capability
**Upgrade Process:**
1. Deploy new contract version
2. Update role addresses to point to new contracts  
3. Verify distribution flows to new contract addresses
**Upgradeable Components:**
Documents all versioned contracts under `gno.land/r/gnoswap/{version}/`:
- pool - Liquidity pool management
- position - Position management  
- router - Swap routing engine
- staker - Staking and rewards
- governance - Governance system (governance, staker, xgns)
- …
> chore: upgrade contract docs

- contract/r/gnoswap/v1/gov/staker/counter.gno
- contract/r/gnoswap/v1/gov/staker/delegation.gno
- contract/r/gnoswap/v1/gov/staker/delegation_history.gno
- contract/r/gnoswap/v1/gov/staker/delegation_test.gno
- contract/r/gnoswap/v1/gov/staker/emission_reward_mananger.gno
- contract/r/gnoswap/v1/gov/staker/emission_reward_state.gno
- contract/r/gnoswap/v1/gov/staker/emission_reward_state_test.gno
- contract/r/gnoswap/v1/gov/staker/protocol_fee_reward_manager.gno
- contract/r/gnoswap/v1/gov/staker/protocol_fee_reward_state.gno
- contract/r/gnoswap/v1/gov/staker/staker_delegate.gno
- contract/r/gnoswap/v1/gov/staker/staker_delegate_test.gno
- contract/r/gnoswap/v1/launchpad/reward_manager.gno
- contract/r/gnoswap/v1/pool/pool.gno
- contract/r/gnoswap/v1/pool/position.gno
- contract/r/gnoswap/v1/pool/swap.gno
- contract/r/gnoswap/v1/pool/tick.gno
- contract/r/gnoswap/v1/position/burn.gno
- contract/r/gnoswap/v1/position/errors.gno
- contract/r/gnoswap/v1/position/mint.gno
- contract/r/gnoswap/v1/router/base.gno
- contract/r/gnoswap/v1/router/errors.gno
- contract/r/gnoswap/v1/router/protocol_fee_swap.gno
- contract/r/gnoswap/v1/router/router.gno
- contract/r/gnoswap/v1/router/router_test.gno
- contract/r/gnoswap/v1/staker/reward_calculation_pool.gno
- contract/r/gnoswap/v1/staker/reward_calculation_pool_tier.gno
- contract/r/gnoswap/v1/staker/reward_calculation_tick.gno
This PR implements the first phase of GnoSwap's comprehensive overflow handling policy, specifically addressing fee growth accumulators that require natural overflow behavior for mathematical correctness.
GnoSwap establishes a systematic approach to overflow handling based on the mathematical properties and financial implications of different value types. This policy ensures optimal balance between protocol safety and computational efficiency.
- **Definition**: Values that continuously accumulate over time using modular arithmetic
- **Policy**: Allow natural overflow without panic handling
- **Mathematical Foundation**: Difference calculations `(a - b) mod 2^256` remain accurate post-overflow
- **Safety Guarantee**: Relative value relationships preserved through modular arithmetic …
> feat: remove panic handling on overflow

- contract/r/gnoswap/v1/pool/pool.gno
- contract/r/gnoswap/v1/pool/pool_test.gno
- contract/r/gnoswap/v1/pool/position.gno
- contract/r/gnoswap/v1/pool/position_test.gno
- contract/r/gnoswap/v1/position/burn.gno
- contract/r/gnoswap/v1/position/mint.gno
- contract/r/gnoswap/v1/position/position.gno
- contract/r/gnoswap/v1/position/position_test.gno
- contract/r/scenario/position/position_multi_user_same_key_filetest.gno
This PR refactors position key generation to follow the Uniswap V3 model, changing from owner-address-based keys to contract-address-based keys. This enables unified position management at the pool level, improving efficiency and aligning with industry standards.
**Adopting Uniswap V3 Architecture**:
- **Previous approach**: `owner_address + tick_lower + tick_upper` - distributed position management per user
- **New approach**: `contract_address + tick_lower + tick_upper` - unified position management in pool contract
This change follows Uniswap V3's proven design philosophy:
1. **Centralized Position Management**: Pool contract serves as the single source of truth for all positions
2. **Efficient Liquidity Aggregation**: Better aggregation and management of positions within the same tick …
> fix: compute position key to unify

- contract/r/gnoswap/v1/gov/governance/governance_propose.gno
- contract/r/gnoswap/v1/launchpad/launchpad_project.gno
- Fix a invalid event data.
- `CreateProject` event in launchpad.
- `ProposeText`, `ProposeCommunityPoolSpend`, `ProposeParameterChange` event in governance.
> fix: fix invalid event data

- contract/r/gnoswap/v1/pool/README.md
- contract/r/gnoswap/v1/pool/manager.gno
This PR adds comprehensive documentation for pool creation griefing attacks and their recovery mechanisms. The documentation addresses a known vulnerability where pools can be initialized with arbitrary prices without validation, and provides detailed guidance on how to recover from such attacks.
**Added Pool Creation Griefing Section to README.md**:
- Detailed explanation of the griefing attack vector
- Impact assessment on pool usability
- Step-by-step recovery mechanism
- Example atomic transaction for pool restoration
- Prevention strategies and monitoring recommendations
**Updated CreatePool Function Documentation**:
- Added security warnings about arbitrary price initialization
- Documented the lack of price validation as an intentional design choice
- Included recovery guidance …
> chore(docs): recover pool initialization griefing attack guide

- contract/r/gnoswap/v1/staker/external_incentive.gno
- contract/r/gnoswap/v1/staker/getter.gno
- contract/r/gnoswap/v1/staker/json.gno
- contract/r/gnoswap/v1/staker/reward_calculation_incentives.gno
- contract/r/gnoswap/v1/staker/reward_calculation_pool.gno
- contract/r/gnoswap/v1/staker/staker.gno
- contract/r/gnoswap/v1/staker/type.gno
- contract/r/gnoswap/v1/staker/utils.gno
- contract/r/scenario/staker/external_incentive_complete_distribution_filetest.gno
- contract/r/scenario/staker/external_incentive_drain_filetest.gno
- contract/r/scenario/staker/external_incentive_dust_refund_filetest.gno
- contract/r/scenario/staker/external_incentive_refund_gnot_filetest.gno
- contract/r/scenario/staker/external_incentive_refund_wugnot_filetest.gno
- contract/r/scenario/staker/single_gns_external_ends_filetest.gno
- contract/r/scenario/staker/staker_native_create_collect_unstake_with_finish_filetest.gno
This pull request addresses two critical fixes in the external incentive mechanism of the staker contract:
The logic for calculating the actual distribution of external rewards has been significantly improved when an incentive period concludes. Previously, the refund calculation did not accurately account for the rewards that were actually distributed to stakers during the incentive period.
**Key Changes:**
- Enhanced the `endExternalIncentive` function to iterate through all deposits and calculate the total external rewards based on each position's last collection time and the incentive's end timestamp
- Introduced the `calculateTotalExternalReward` method that accurately computes rewards distributed to positions throughout the incentive duration
- Added the `distributedRewardAmount` …
> fix(staker): calculate actual distribution external rewards when end incentive

- contract/r/gnoswap/v1/staker/calculate_pool_position_reward.gno
- contract/r/gnoswap/v1/staker/external_incentive.gno
- contract/r/gnoswap/v1/staker/reward_calculation_incentives.gno
- contract/r/gnoswap/v1/staker/reward_calculation_pool.gno
- contract/r/gnoswap/v1/staker/reward_calculation_pool_tier.gno
- contract/r/gnoswap/v1/staker/type.gno
- contract/r/scenario/staker/external_incentive_dust_refund_filetest.gno
This pull request implements comprehensive safe arithmetic operations for int64 calculations throughout the staker contract to prevent overflow and underflow errors that could compromise the integrity of reward calculations and financial operations.
The staker contract performs numerous arithmetic operations on int64 values for reward calculations, including additions, multiplications, and accumulations across various components. Without proper overflow/underflow protection, these operations could silently produce incorrect results, leading to:
- Inaccurate reward distributions
- Potential loss of funds
- System state corruption
- Unexpected contract behavior
The contract now includes three core safe arithmetic functions in `utils.gno`:
- **`safeAddInt64(a, b int64) int64`**: Performs …
> fix(staker): handle safe int64 calculation

- contract/r/gnoswap/v1/staker/staker.gno
> fix(staker): handle archived incentives
