gnoswap-labs/gnoswap

staker/_TEST_staker_one_external_test.gnoa
staker/_TEST_staker_one_increase_external_test.gno
staker/incentive_id.gno
staker/staker.gno

- allow creating external incentive with same targetPath, rewardToken
- includes caller address to support this

GSW-358 feat: use caller address when calculation incentive id

---

pool/_RPC_api.gno

- return entire `tickBitmap` object in pool rpc
change was requested by @jinoosss

GSW-579 chore return entire `tickbitmap` value in pool rpc api

---

_test/init_only.mk
deployer.sh

- deployer will exeucte `init_only.mk` as entrypoint 
- when mk execution finish > it sends `1ugnot` to ~`position`~ `gov` contract

GSW-616 send `1ugnot` to gov

---

staker/_TEST_init_test.gno
staker/_TEST_staker_collect_reward_test.gnoa
staker/_TEST_staker_one_external_native_test.gnoa
staker/_TEST_staker_one_external_test.gnoa
staker/_TEST_staker_one_increase_external_test.gno
staker/staker.gno

- if incentive creator doesn't call EndExternal() after duration time is over, certain address can call it without refund

GSW-698 feat: allow certain address to execute end external only when time is over

---

pool/tick.gno

- wrong base number was used when calculation max liquidity for tick spacing
---
bug was discovered by @jinoosss

GSW-705 fix: tickSpacing maxLiquidity calculation

---

pool/_TEST_tick_math_test.gno
pool/tick_math.gno

1. Extract tick ratio values into map (`tickRatioMap`)
2. Extracted the individual logic of the `TickMathGetTickAtSqrtRatio` function into functions.

refactor: pool/tick_math.gno

---

position/_GET_position.gno
position/_RPC_api.gno
position/_RPC_dry.gno
position/liquidity_amounts.gno
position/liquidity_management.gno

1. Elimination of Duplicate Code: Implemented a logic to automatically swap the values of `sqrtRatioA` and `sqrtRatioB` using the `swapIfGreater` function without duplication.
2. Function Name Change: Functions that are only used in the `liquidity_amounts.gno` file have been renamed to `computeXXX`, while functions called from other places have been prefixed with `GetXXX`."

refactor: position/liquidity_amounts

---

pool/liquidity_math.gno
pool/liquidity_math_test.gno

When the result(`z`) became negative is generally due to the incorrect input values. For example, if `x` is negative and `y` is a positive number that is less than the absolute value of that negative number (e.g., x=-100, y=50). Here, `z` turn out to be negative value(-50). Another case is when both input values are negative.
So I think it's sufficient to simply check that `z` is negative.

Remove unnecessary checks from `liquidityMathAddDelta` function

---

consts/consts.gno
position/_RPC_api.gno
position/_TEST_INIT_register_tokens_test.gno
position/_TEST_position_api_test.gnoa
position/_TEST_position_test.gno
position/gno.mod
position/gno_helper.gno
position/liquidity_management.gno
position/position.gno
position/test_helper.gno

- unused value in consts
- change hardcoded value in position to value from consts

GSW-871 feat: use common consts

---

_setup/gnft/gnft.gno
_setup/gns/gns.gno
consts/consts.gno
pool/_TEST_INIT_register_tokens_test.gno
position/_TEST_INIT_register_tokens_test.gno
router/_TEST_INIT_basic_test.gno
router/_TEST_INIT_register_tokens_test.gno
router/router_register.gno
staker/_TEST_INIT_basic_test.gno
staker/_TEST_INIT_register_tokens_test.gno
staker/_TEST_staker_collect_reward_test.gno
staker/_TEST_staker_get_test.gnoa
staker/_TEST_staker_internal_external_test.gnoa
staker/_TEST_staker_one_external_native_test.gnoa
staker/_TEST_staker_one_external_test.gnoa
staker/_TEST_staker_one_increase_external_test.gnoa
staker/_TEST_staker_rpc_test.gnoa
staker/reward_math.gno
staker/staker.gno
staker/staker_register.gno

1. more condition to calculate staking reward https://github.com/gnoswap-labs/gnoswap/commit/128dd4f7535d3ee8432154369791aebff8d35431
2. better comments :D
3. bunch of tc

GSW-872 detailed condition to check staking reward

---

staker/staker.gno

`LiquidityAmountsGetAmountsForLiquidity` -> `GetAmountsForLiquidity`

chore(staker): Fix wrong function name in staker

---

_test/_TEST_INIT_basic_test.gno
_test/_TEST_INIT_register_tokens_test.gno
_test/_TEST_scenario_01_full_happy_case_test.gnoa
_test/_TEST_scenario_02_FAIL_too_small_amount_test.gnoa
_test/_TEST_scenario_03_FAIL_too_small_liquidity_test.gnoa
_test/_TEST_scenario_04_router_one_route_one_hop_test.gnoa
_test/_TEST_scenario_05_router_one_route_two_hop_test.gnoa
_test/_TEST_scenario_06_router_one_route_three_hop_println_test.gnoa
_test/_TEST_scenario_07_FAIL_router_one_route_three_hop_large_amount_println_test.gnoa
_test/_TEST_scenario_08_router_two_position_one_route_one_hop_println_test.gnoa
_test/_TEST_scenario_98_router_only_upper_position_println_test.gnoa
_test/_TEST_scenario_99_router_uniswap_sdk_test.gno
_test/swap_scenario.gno
pool/TEST_liquidity_math_test.gnoa
pool/type.gno
position/type.gno
router/type.gno
staker/staker.gno
staker/type.gno

1. (scenario) test cases
@notJoon @mconcat
just to remind you, each contract has its own test cases in same folder for unit testing
To test full progress of gnoswap, it has `_test` folder at root location with some scenarios. Please run these test cases too when everything is fine with unit tests.
FYI, you're very welcome to add more scenarios

GSW-873 fix: test cases under `_test` folder ≈ based on scenario

---

position/liquidity_management.gno
position/position.gno
position/type.gno

1. support increase or decrease liquidity for existing position
wait for #173 #174 #175 #176

GSW-793 feat support increase decrease liquidity for positions

---

_setup/gns/gns.gno
consts/consts.gno
pool/pool_manager.gno
pool/type.gno
position/liquidity_management.gno
position/position.gno
position/type.gno
router/_TEST_INIT_basic_test.gno
router/comptue_routes.gno
router/type.gno
staker/_TEST_INIT_basic_test.gno
staker/_TEST_staker_rpc_get_test.gno
staker/staker.gno
staker/type.gno

1. handled some of comments
wait for existing prs

GSW-877 feat: implement some todos

---

common/_TEST_tick_math_test.gno

Added tests for `tick_math`, mostly targeting public functions, but also writing tests for functions that seemed to need their own tests.
- `TickMathGetSqrtRatioAtTick`
- `TickMathGetTickAtSqrtRatio`
- `calculateLog2`
#118 
Reopen a PR(#184) that was unexpectedly closed. 
---
_**The issue came from this following [comments](https://onbloc.slack.com/archives/C0391ED6TPZ/p1709085982973049?thread_ts=1709084136.178529&cid=C0391ED6TPZ)**_

GSW-887: Create test case for tick math (2)

---

__local/grc20_tokens/register_gnodev/gno.mod
__local/grc20_tokens/register_gnodev/register_gnodev.gno
__local/test/test_data.mk
_deploy/r/gnoswap/common/liquidity_amounts.gno
_deploy/r/gnoswap/consts/consts.gno
pool/_RPC_api.gno
pool/pool_manager.gno
position/_RPC_api.gno
position/position.gno
router/_RPC_api.gno
router/router.gno
staker/staker.gno

1. makefile testing covers most of function
2. api json field names are being changed due to rdb refactor
draft for now, expecting bit of makefile test changes

GSW-1005 test makefiles to execute most of function

---

pool/_TEST_/z1_single_lp_filetest.gno
position/_TEST_/_TEST_position_increase_decrease_test.gn
router/_TEST_/_TEST_router_ratio_test.gn
router/_TEST_/_TEST_router_swap_route_1route_1hop_test.gn
router/_TEST_/_TEST_router_swap_route_1route_3hop_wrapped_native_middle_test.gn
router/_TEST_/_TEST_router_swap_route_2route_2hop_test.gn
staker/_RPC_api_incentive.gno
staker/_TEST_/_TEST_staker_collect_reward_test.gn
staker/_TEST_/_TEST_staker_get_test.gn
staker/_TEST_/_TEST_staker_internal_external_test.gn
staker/_TEST_/_TEST_staker_one_external_native_test.gn
staker/_TEST_/_TEST_staker_one_external_test.gn
staker/_TEST_/_TEST_staker_one_increase_external_test.gn
staker/_TEST_/_TEST_staker_rpc_get_test.gn
staker/staker.gno

1. start time of `CreateExternalIncentive` must satisfy following conditions
1.1 Must be same or bigger(later ≈ future) than tomorrow midnight.
1.2 Must be midnight of day
2. new api function for incentive lists
3. fix panic conditions by change start time of external incentive

GSW-1012 feat: conditions for external incentive start time

---

pool/pool_manager.gno

1. `pool - CreatePool()` was returning struct, which was only for testing
- causing `block_results` unexpected behavior

fix: remove struct (which isn't primitive type, causing bunch of eror) return

---

staker/staker.gno

1. time range for incentive creation must be in seconds format
2. endTimestamp can not be later then '9999-12-31 23:59:59'

GSW-1035 feat: check normal time-range for incentive creation

---

pool/_RPC_api.gno

1. ApiGetPool(`poolPath`) to retrieve single pool

GSW-1032 feat: ApiGetPool(poolPath) to retrieve single pool information

---

_deploy/p/demo/gnoswap/pool/sqrt_price_math.gno
_deploy/r/demo/gnoswap/common/sqrt_price_math.gno
_deploy/r/demo/gnoswap/consts/consts.gno
gov/api.gno
gov/const.gno
gov/realm_variables.gno
gov/tally.gno
pool/_RPC_api.gno
pool/_RPC_dry.gno
position/_RPC_api.gno
position/position.gno
position/wrap_unwrap.gno
router/comptue_routes.gno
router/router.gno
router/swap_multi.gno
router/wrap_unwrap.gno
staker/_RPC_api_incentive.gno
staker/_RPC_api_stake.gno
staker/reward_math.gno
staker/staker.gno
staker/staker_parameters.gno
staker/utils.gno

1. support gno's static [analysis](https://github.com/gnolang/gno/pull/1750)

build: apply gno's new static analysis

---

position/position.gno

1. remove unused variable (results deploy error)
> it was used, but was meant to be removed from previous pr #234

hotfix: remove unused variable (results deploy error)

---

position/_TEST_/__TEST_position_mint_gnot_grc20_in-range_out-range_test.gnoA
position/position.gno

1. (for position with ugnot coin), fix: insufficient allowance
> when amount of sent coins was left, unwrap logic was wrong

GSW-1136 fix: insufficient allowance when add liquidity(for position with ugnot coin)

---

position/_TEST_/__TEST_0_INIT_VARS_HELPERS_test.gno
position/_TEST_/__TEST_position_increase_burned_position_test.gnoA
position/position.gno

1. if target position is `burned`, can not increase liquidity

GSW-1195 fix: cannot increase liquidity for burned position

---

__local/test/all_test_data.mk
__local/test/emission_test.mk
router/router.gno
router/tests/__TEST_router_all_2_route_2_hop_with_emission_test.gnoA
router/tests/__TEST_router_swap_route_1route_1hop_native_in_out_test.gnoA

1. do not use pre-exising wugnot balance when swapping ugnot
- selecting ugnot => use only ugnot coin
- selecting wugnot => use only wugnot token

GSW-1399 fix do not use existing wugnot balance when swapping ugnot

---

README.md
setup.py

Since the contract's paths are updated to `v2`, I modified the previous setup script to move it to copy/move the v2 subdirectory.

chore: Copy files to v2 subdirectory and Readme

---

position/_GET_no_receiver.gno.gno
position/_RPC_api.gno
position/position.gno
position/tests/__TEST_fee_collect_with_two_user_test.gnoA
position/tests/__TEST_position_api_test.gnoA
position/tests/__TEST_position_native_mint_swap_burn_test.gnoA
position/tests/__TEST_position_reposition_gnot_pair_test.gnoA
position/tests/__TEST_position_reposition_grc20_pair_test.gnoA
position/tests/__TEST_position_reposition_grc20_pair_with_swap_test.gnoA
position/tests/__TEST_position_same_user_same_pool_diff_range_diff_position_swap_fee_test.gnoA
position/tests/__TEST_position_same_user_same_pool_same_range_diff_position_swap_fee_test.gnoA
position/tests/__TEST_position_tokens_owed_left_grc20_pair_more_action_test.gnoA
position/tests/__TEST_position_tokens_owed_left_pair_more_action_exact_test.gnoA
staker/staker.gno
staker/tests/__TEST_staker_NFT_transfer_01_test.gnoA
staker/tests/__TEST_staker_NFT_transfer_02_test.gnoA
staker/tests/__TEST_staker_NFT_transfer_03_test.gnoA

1. by default, position's operator will be ZERO_ADDRESS
2. when position is staked, update operator to caller
3. when position is unstaked, update(reset) operator to ZERO_ADDRESS
1. add three test cases with nft being transfered

GSW-1883 feat: update position operator based on behavior

---

launchpad/launchpad_reward.gno
launchpad/tests/__TEST_launchpad_tier180_single_deposit_reward_by_proejct_test.gnoA
launchpad/tests/__TEST_launchpad_tier_all_single_deposit_reward_by_proejct_tier_test.gno

1. launchpad pool reward calculation
- if pool is inactive, do not update last calculated height

GSW-1902 fix: launchpad pool reward calculation

---

_deploy/p/gnoswap/uint256/uint256.gno
gov/governance/util.gno
launchpad/util.gno

Remove all the unused `uintSize` and some `MaxUint64` const values

chore: Remove Unused Consts

---

staker/reward_recipient_store.gno

- when generate emission reward recipient, use clone value for liquidity

GSW-1959 fix: use clone liquidity to calculate emission

---

staker/_RPC_api_calculation_base_data.gno
staker/calculate_pool_position_reward.gno
staker/reward_recipient_store.gno
staker/staker.gno

1. get position's liquidity in string, then assign it to uint256
> logic changed in this pr doesn't change liquidity, therefore need to aviod accessing pointer value directly.

GSW-1959 fix: get position's liquidity in string, then assign it to uint256

---

gov/staker/staker.gno
gov/staker/tests/__TEST_0_INIT_VARIABLE_AND_HELPER_test.gno
gov/staker/tests/__TEST_governance_reward_protocol_fee_test.gnoA
gov/staker/util.gno
router/protocol_fee_swap.gno

1. collect and distribute protocol_fee in grc20, when unwrap when user requests claiming it.

GSW-1967 fix: ugnot protocol_fee wasn't being distributed

---

_deploy/r/gnoswap/common/strings.gno
gov/governance/_GET_vote.gno
gov/governance/vote.gno
launchpad/launchpad_deposit.gno
position/utils.gno
router/comptue_routes.gno
router/utils.gno
staker/utils.gno

* modified the part where strings were concatenated using the `+` operator to use a formatting function instead.
- This change was made for readability rather than performance concerns (generally, using the `+` operator for string concatenation can result in minor performance degradation). 
* extracted the logic for splitting strings with a specific separator into a common utility.

chore: Remove String Concat With `+` Operator

---

pool/liquidity_math.gno

Simple readability improvement.
Previously, we used the not operator (!) for processing, but in that case it was quite difficult to understand.

refactor: liquidity_math

---

pool/helper_test.gno

1. helper to reset all state in pool
2. burn all tokens for addresses used during tests

test: helper to reset pool state

---

_deploy/r/gnoswap/common/halt.gno
_deploy/r/gnoswap/common/halt_test.gno

1. `common` has new privileges check logic(#390), therefore apply it.

GSW-1968 refactor: use latest privileges access check logic

---

pool/_helper_test.gno
pool/gno.mod

- remove require in gno.mod
- use getter function in test code

GSW-2023 chore: update gno.mod and use getter function in test code

---

pool/getter.gno
pool/pool.gno
pool/position.gno
pool/tick.gno
position/_RPC_api.gno
position/liquidity_management.gno
position/position.gno

1. remove `Pool` prefix from pool's receiver getter funcs

GSW-1838 chore: remove prefix from pool's receiver getter

---

_deploy/r/gnoswap/common/access.gno
_deploy/r/gnoswap/common/access_test.gno
_deploy/r/gnoswap/common/gno.mod

1. `EmissionOnly` checks whether caller is emisson contract or not
2. add unittest
3. remove deprecated `require` from gno.mod

GSW-1968 feat: check emission is caller or not

---

pool/_helper_test.gno
pool/api.gno
pool/api_test.gno
pool/getter.gno
pool/getter_test.gno
pool/pool.gno
pool/pool_manager.gno
pool/pool_manager_test.gno
pool/pool_test.gno
pool/position.gno
pool/position_update.gno
pool/position_update_test.gno
pool/protocol_fee_withdrawal_test.gno
pool/swap_test.gno
pool/tick.gno
pool/tick_bitmap.gno
pool/tick_bitmap_test.gno
pool/tick_test.gno
pool/type.gno
pool/utils.gno

1. use `avl.Tree` instead of `map`
- currently `map` has issue with processing pointer value as key

GSW-1838 refactor: use avl.Tree in pool

---

_deploy/r/gnoswap/common/address_and_username.gno
_deploy/r/gnoswap/common/address_and_username_test.gno
_deploy/r/gnoswap/common/errors.gno
_deploy/r/gnoswap/common/gno.mod
_deploy/r/gnoswap/common/grc20reg_helper.gno
_deploy/r/gnoswap/common/grc20reg_helper_test.gno
_deploy/r/gnoswap/common/grc721_token_id.gno
_deploy/r/gnoswap/common/grc721_token_id_test.gno
_deploy/r/gnoswap/common/math.gno
_deploy/r/gnoswap/common/math_test.gno

1. implements commonly used functions 
- it must be a public function

GSW-1968 refactor: commonly used functions

---

_deploy/p/gnoswap/uint256/arithmetic.gno
_deploy/p/gnoswap/uint256/arithmetic_test.gno

The `IsOverflow()` function checks if a uint256 number has overflowed by examining the 255th bit (the most significant bit). In uint256, the valid range is from 0 to 2^255-1, so any number with the 255th bit set is considered an overflow.

feat: `uint256` single value overflow checker

---

staker/reward_calculation_warmup.gno
staker/reward_calculation_warmup_test.gno

- Verify default warmup stages (5, 10, 30 days)
- Validate correct warmup ratios (30%, 50%, 70%, 100%)
- Check block duration calculations
- Test various warmup ratios (30%, 50%, 70%, 100%)
- Verify reward and penalty calculations
- Handle edge cases with small and large numbers
- Ensure rounding behavior in integer division
- Test different position/staked liquidity ratios
- Validate calculations with various pool sizes
- Check boundary conditions (very small/large ratios)
- Verify correct warmup stage identification
- Test boundary conditions between stages
- Validate warmup height calculations
- Handle zero values
- Test maximum uint64 values
- Verify calculation precision with small numbers
- Ensure total rewards + penalties match expected values

test(staker): reward calculation warmup

---

referral/doc.gno
referral/errors.gno
referral/global_keeper.gno
referral/gno.mod
referral/keeper.gno
referral/keeper_test.gno
referral/referral.gno
referral/type.gno
referral/utils.gno
setup.py

This PR introduces a referral system that allows authorized contracts to manage referral relationships between addresses. The system enables tracking and managing referrer-referee relationships.
```mermaid
classDiagram
class ReferralKeeper {
<<interface>>
+register(addr, refAddr std.Address)
+update(addr, newAddr std.Address)
+remove(addr std.Address)
+has(addr std.Address)
+get(addr std.Address)
}
class Keeper {
-store *avl.Tree
+register(addr, refAddr std.Address)
+update(addr, newRefAddr std.Address)
+remove(addr std.Address)
+has(addr std.Address)
+get(addr std.Address)
}
class Referral {
-keeper ReferralKeeper
+Register(addr, refAddr std.Address)
+Update(addr, newRefAddr std.Address)
+Remove(addr std.Address)
+Has(addr std.Address)
+Get(addr std.Address)
}
Referral --> ReferralKeeper …
```

feat: referral

---

contract/r/gnoswap/v1/staker/README.md

Update staker README.md

---

contract/r/gnoswap/gns/gns.gno
contract/r/gnoswap/gns/gns_test.gno

1. Remove unnecessary function in gns
> related manfred comment https://github.com/gnoswap-labs/gnoswap/pull/465#discussion_r1923307199 
2. use Token object if possible
> since Token is read-only object, it is safer

refactor: remove unnecessary functions from the gns realm

---

contract/p/gnoswap/rbac/doc.gno
contract/p/gnoswap/rbac/gno.mod
contract/p/gnoswap/rbac/rbac.gno
contract/p/gnoswap/rbac/rbac_test.gno
contract/p/gnoswap/rbac/role.gno

Implemented the RBAC package, but need to discussion whether it should be located in `p` or `r`.
paritally related with #496

feat(p/rbac): RBAC Pacakge Implementation

---

contract/r/gnoswap/router/router_dry.gno
contract/r/gnoswap/router/router_dry_test.gno
contract/r/gnoswap/router/router_test.gno
contract/r/gnoswap/router/tests/router_all_2_route_2_hop_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_out_range_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_wrapped_native_in_out_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_2hop_wrapped_native_in_out_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_3hop_wrapped_native_middle_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_2route_2hop_test.gnoA

Change the return value of dryswap.
The return value is the result of the swap simulation and is expressed as follows.
amount0, amount1, swapability (bool)

refactor: change dryswap return value

---

contract/r/gnoswap/router/base.gno
contract/r/gnoswap/router/exact_out.gno
contract/r/gnoswap/router/tests/router_spec_#5_ExactOut_test.gnoA

Fix for the case where the input token is gnot and the swap is of the exact-out type, and the swap fails due to an asset shortage error because the native cannot be wrapped

fix: when input token is native and exact-out type, swap fail

---

contract/r/gnoswap/gov/staker/reward.gno
contract/r/gnoswap/gov/staker/reward_test.gno

When a user attempts to partially undelegate their staked `GNS` tokens, the current `removeStake` completely removes the staker's information from the state, regardless of the undelegation amount.
This lead to:
- Loss of remaining delegation information
- Loss of rewards for the delegation information
- Incorrect total stake calculation
Modified the `removeStake` function to:
1. Preserve staker information for partial undelegations
2. Only remove staker information when the entire amount is undelegated
3. Correctly update stake amount for partial undelegations
- Added checker that checks if undelegation amount equals total staked amount
- For partial undelegations:
- Maintain staker info in state
- Subtract only the desire amount from stake
- For complete undelegations:
- Remove staker …

fix: Complete Stake Wipeout on Partial Undelegation

---

contract/r/gnoswap/launchpad/launchpad_deposit.gno
contract/r/gnoswap/launchpad/launchpad_deposit_test.gno

The `processDepositCollection` function was incorrectly requiring all depositors to wait until the project ends before withdrawing their GNS tokens. This was due to the condition `currentHeight < project.Ended().height` which prevented withdrawals before project completion.
- Removed the project end height check from `processDepositCollection`
- Each deposit can now be collected independently based on its individual claimable height
- Code tidy
Added two new test cases:
1. `TestProcessDepositCollection_ClaimableLogic`
- Tests multiple deposits with different claimable heights
- Verifies that deposits can be collected independently
- Validates correct handling of claimable and non-claimable deposits
2. `TestProcessDepositCollection_ProjectEndCondition`
- Tests deposit collection before …

fix: Update deposit collection logic to prevent delayed withdrawals

---

contract/r/gnoswap/pool/pool_type.gno

The `tickCrossHook` is a global variable, it doesn't need to be managed by a type.

chore: remove `tickCrossHook` from `Pool` type

---

contract/r/gnoswap/pool/position_test.gno
contract/r/gnoswap/pool/tick.gno
contract/r/gnoswap/pool/tick_test.gno

Fixes an issue where users cannot create Full Range positions in pools with 0.01% fee tier. The problem was in the `assertValidTickUpper` function in `tick.gno`, which incorrectly rejected valid tick upper values equal to `MAX_TICK`.
- `tickUpper >= consts.MAX_TICK` -> `tickUpper > consts.MAX_TICK`

GSW-2216 fix: Unable to create Full Range position in 0.01% fee pool

---

contract/r/gnoswap/router/router.gno
contract/r/gnoswap/router/router_test.gno
contract/r/gnoswap/router/tests/router_all_2_route_2_hop_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#1_ExactIn_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#2_ExactIn_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#3_ExactIn_test.gnoA

The `ExactOutSwap` operation is failing with a slippage check error. The error occurs when there is a difference of just `1` unit between the requested output amount and the actual output amount.
```plain
[GNOSWAP-ROUTER-002] slippage check failed || Received more than requested in [EXACT_OUT] requested=600901352, actual=600901351
```
The issue occurs from the precision handling in the `finalizeSwap` function. In the `ExactOut` swap type, the function checks if `resultAmountOut` is less than `amountSpecified`:
```go
if resultAmountOut.Lt(amountSpecified) {
panic(addDetailToError(
errSlippage,
ufmt.Sprintf("Received more than requested in [EXACT_OUT] requested=%s, actual=%s", amountSpecified.ToString(), resultAmountOut.ToString()),
))
}
```
This check fails when there is even a 1-unit …

GSW-2213 fix: Slippage error in ExactOut

---

contract/p/gnoswap/int256/cmp.gno
contract/r/gnoswap/router/base.gno
contract/r/gnoswap/router/exact_in.gno
contract/r/gnoswap/router/exact_out.gno
contract/r/gnoswap/router/router.gno
contract/r/gnoswap/router/router_dry.gno
contract/r/gnoswap/router/router_dry_test.gno
contract/r/gnoswap/router/tests/router_spec_#4_ExactIn_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#5_ExactOut_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#6_ExactOut_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#7_ExactOut_test.gnoA
contract/r/gnoswap/router/tests/router_spec_#8_ExactOut_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_all_liquidity_exact_in_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_all_liquidity_exact_out_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_out_range_test.gnoA
contract/r/gnoswap/router/tests/router_swap_route_1route_1hop_test.gnoA

In the dry swap, may overflow in the following two cases:
1. During quote calculation in `calculateSwapAmount`
2. When accumulating results in `resultAmountIn` and `resultAmountOut`
- Added `IsOverflow` function to `int256` package
- Added overflow check in `calculateSwapAmount` and `DrySwapRoute` functions in the `router_dry.gno` file
- Added related tests
- Need to run separately because it creates the pool within the test
- Refactored `router.gno` file

GSW-2214 feat: Add Overflow Protection to `DrySwapRoute`

---

contract/r/gnoswap/pool/pool_type.gno
contract/r/gnoswap/pool/swap.gno

* **Added `Ticks` method to `Pool` struct**: This method iterates over the `ticks` AVL tree, converts each tick's data into a JSON-like string format, and returns a concatenated string representation of all ticks. (`contract/r/gnoswap/pool/pool_type.gno`, [contract/r/gnoswap/pool/pool_type.gnoR79-R102](diffhunk://#diff-aff118d48fc271a85312e9706162cf06f2b8fd3a4e2b687f2a8286700c078b4bR79-R102))
* **Updated `Swap` function to include tick data**: The `Swap` function now calls the new `Ticks` method and includes the resulting tick data in its output. (`contract/r/gnoswap/pool/swap.gno`, [contract/r/gnoswap/pool/swap.gnoR133](diffhunk://#diff-2e80ee12d605a9afabc1424c74775545c4dfa7e0c7b7999a368069aa65b6a771R133))

feat: Emit ticks information from Swap events

---

.github/workflows/run_test.yml

temporarily pin the repository reference to a before interrealm(https://github.com/gnolang/gno/pull/4060) commit instead of the `master` branch. 
Need to revert this change after the problem has been resolved.

hotfix: Temporary pin the gnolang version before interrealm

---

contract/r/gnoswap/position/position.gno

Update `Mint` function's event to emit the `token0Balance` and `token1Balance`. These values were retrieved directly from the pool via the pool path.
**Output**
```diff
{
"type": "Mint",
"attrs": [
{
"key": "prevAddr",
"value": "g17290cwvmrapvp869xfnhhawa8sm9edpufzat7d"
},
{
"key": "prevRealm",
"value": ""
},
{
"key": "tickLower",
"value": "-887270"
},
{
"key": "tickUpper",
"value": "887270"
},
{
"key": "poolPath",
"value": "gno.land/r/onbloc/bar:gno.land/r/onbloc/foo:500"
},
{
"key": "mintTo",
"value": "g17290cwvmrapvp869xfnhhawa8sm9edpufzat7d"
},
{
"key": "caller",
"value": "g17290cwvmrapvp869xfnhhawa8sm9edpufzat7d"
},
{
"key": "lpPositionId",
"value": "12"
},
{
"key": "liquidity",
"value": "50000"
},
{
"key": "amount0",
"value": "50000"
},
{
"key": "amount1",
"value": "50000"
},
{ …
```

GSW-2260 feat(position): Update `Mint` function's event to include token balances

---

contract/r/gnoswap/referral/global_keeper.gno
contract/r/gnoswap/referral/keeper.gno
contract/r/gnoswap/referral/keeper_test.gno

The existing implementation had a condition that required waiting for 24 hours before attempting to register a referral again, even when the previous attempt had failed.
So, modified the code to store the success status along with the referral information for each address. Now, the time check is only performed when the previous referral registration was successful; otherwise, the check is skipped.
Additionally, I added an error field to the events emitted when the `TryRegister` function fails, so that the specific reason for failure is also output.
For example:
```json
[
{
"type": "ReferralRegistrationFailed",
"attrs": [
{
"key": "address",
"value": "g1weskc6tyx9047h6lta047h6lta047h6lwtjkk9"
},
{
"key": "error",
"value": "invalid address format"
}
],
"pkg_path": …
```

GSW-2258 fix: referral time checks

---

contract/r/gnoswap/referral/keeper.gno
contract/r/gnoswap/referral/keeper_test.gno

When registering with zero address (`""`), the referral system was incorrectly applying rate limits.
Especially, after that case, subsequent registrations with valid addresses were rate limited.
This fix involves:
- Modifying the `setReferral` function to skip rate limit checks when the referral address is zero
- Ensuring that zero address registratins don't affect the rate limit state.

fix: allow zero address registration without rate limit check

---

contract/r/gnoswap/position/getter.gno

In Uniswap V3, a position should no longer be considered active when the price moves to or beyond its upper tick boundary. However, the current implementation uses `<= position.tickUpper` for range checking, which incorrectly includes the upper boundary tick in the active range.
- Modified the range check condition from `<= position.tickUpper` to `< position.tickUpper`
- This ensures that positions are correctly marked as inactive once the current tick reaches the upper boundary

fix(position): `PositionIsInRange` range check

---

contract/r/gnoswap/staker/errors.gno
contract/r/gnoswap/staker/staker.gno

The `UnStakerToken` allowed any caller to unstake tokens without verifying if they are the actual owner of the deposit. This could potentially lead to unauthorized withdrawal of staked tokens.
Thus, Added explicit owner verification in the `UnStakeToken` function.

fix(staker): Add owner verification in `UnStakeToken`

---

contract/p/gnoswap/rbac/rbac.gno
contract/r/gnoswap/rbac/manager.gno
contract/r/gnoswap/rbac/manager_test.gno

Added owner verification to all administrative functions 
- `RegisterRole`
- `RegisterPermission`
- `RemovePermission`
- `RemoveRole`

feat(rbac): Add owner-only access control to RBAC manager functions

---

contract/r/gnoswap/rbac/manager_test.gno

The RBAC manager tests were failing with "caller is not owner" errors because the globalManager instance was not properly initialized with an owner.
Modified `setupTest()` to initialize `globalManager` with test caller address as the owner.

fix(rbac): Fix RBAC manager tests 

---

contract/r/gnoswap/pool/pool.gno

gno_VM doesn't save gas when avoiding hot storage -> cold storage

fix) omit 1 wei dusting techniq

---

.github/workflows/run_test.yml

fixed to use gno before xform2 version on CI

CI: Use gno before xform2 version

---

contract/r/gnoswap/gns/gns.gno
contract/r/gnoswap/test_token/bar/bar.gno
contract/r/gnoswap/test_token/baz/baz.gno
contract/r/gnoswap/test_token/foo/foo.gno
contract/r/gnoswap/test_token/obl/obl.gno
contract/r/gnoswap/test_token/qux/qux.gno
contract/r/gnoswap/test_token/usdc/usdc.gno

The existing test token implementation was storing and using `UserTeller` as a global variable, which could lead to unintended behavior, so it was changed to have each function directly retrieve and process the corresponding value.

fix(tokens): Remove gloval vars

---

contract/r/gnoswap/gnft/testutils.gno
contract/r/gnoswap/pool/_helper_test.gno
contract/r/gnoswap/pool/getter_test.gno
contract/r/gnoswap/pool/pool.gno
contract/r/gnoswap/pool/testutils.gno
contract/r/gnoswap/position/_helper_test.gno
contract/r/gnoswap/position/api_test.gno
contract/r/gnoswap/position/burn.gno
contract/r/gnoswap/position/getter_test.gno
contract/r/gnoswap/position/liquidity_management_test.gno
contract/r/gnoswap/position/mint.gno
contract/r/gnoswap/position/mint_test.gno
contract/r/gnoswap/position/native_token_test.gno
contract/r/gnoswap/position/position.gno
contract/r/gnoswap/position/position_test.gno
contract/r/gnoswap/position/reposition.gno
contract/r/gnoswap/position/testutils.gno
contract/r/gnoswap/position/type.gno
contract/r/gnoswap/position/utils_test.gno

This PR introduces explicit caller (positionCaller) parameters to position-related methods in the Gnoswap contracts, such as Mint, Burn, DecreaseLiquidity, and CollectFee.
Previously, these methods relied on getPrevAddr() to determine the caller or owner of a position. However, this approach causes critical issues when contracts interact with each other, especially between the pool and position contracts:
- **Incorrect Caller Attribution in Contract-to-Contract Calls**:  
When the pool contract calls the position contract (e.g., during liquidity operations), getPrevAddr() returns the address of the calling contract (the pool), not the original user or intended position owner. This leads to incorrect position key computation, ownership checks, and fee accounting, as the contract address is …

fix: add caller parameters in position methods

---

contract/r/gnoswap/emission/distribution.gno
contract/r/gnoswap/emission/distribution_test.gno

Added validation to ensure `bptPct` cannot exceed 10000

fix(r/emission): Add validation for `bptPct` parameter in `calculateAmount`

---

contract/r/gnoswap/position/utils.gno

This PR refactors the position authorization logic to improve clarity and consistency when checking position ownership and operator permissions.
- **Before**: Used `gnft.GetApproved()` with error handling to check operator status
- **After**: Directly use `PositionGetPositionOperator()` for consistent operator retrieval
- **Benefit**: Eliminates unnecessary error handling and provides a more direct approach
- **Before**: Complex nested logic that checked owner/operator status with additional handling for staked positions
- **After**: Clear separation of logic based on staking status:
- If position is staked → only check operator permissions
- If position is not staked → only check owner permissions
- **Benefit**: Clearer code flow and more predictable authorization behavior
- For **staked …

fix: check position owner and operator

---

contract/r/gnoswap/gns/halving_emission_scenario_test.gno

This PR adds test coverage to verify the correct behavior of GNS token emission calculations when average block time changes, ensuring historical emissions are not retroactively modified.
When `setAvgBlockTimeInMs` is called, it updates emission calculations and triggers `callbackEmissionChange`. There was a concern that `cacheReward` might incorrectly use new emission values for past blocks instead of preserving historical emission rates.
- Added `halving_emission_scenario_test.gno` with comprehensive test scenarios
- Implemented table-driven tests covering 4 critical scenarios:
**a. Basic Emission Update Flow**
- Verifies emission values change correctly and callbacks receive updated values
**b. Historical Block Emission Accuracy**
- Ensures past block emissions remain unchanged after …

test(gns): Test scenarios for GNS emission calculation with block time changes

---

contract/r/gnoswap/emission/leftamount_test.gno

Improved test cases for verifying leftAmount calculation after token distribution in the emission system.
The existing tests had the following issues:
- Lack of clear explanations and expected values for rounding calculations
- Unclear calculation logic in test cases
- Insufficient testing for various distribution ratios

fix: emission left amount tests

---

contract/r/gnoswap/access/access.gno
contract/r/gnoswap/access/access_test.gno

This PR improves encapsulation by converting the `GetCurrentConfig()` function from a public method to an internal method `getCurrentConfig()`, restricting direct external access to the configuration pointer and following Go's encapsulation principles.
- **Before**: `GetCurrentConfig()` - Public function (exported)
- **After**: `getCurrentConfig()` - Internal function (unexported)
```go
// Before: Public access
func GetCurrentConfig() *config {
if currentConfig == nil {
return nil
}
return currentConfig
}
// After: Internal access only
func getCurrentConfig() *config {
if currentConfig == nil {
return nil
}
return currentConfig
}
```
- Updated all test file references from `GetCurrentConfig()` to `getCurrentConfig()`
- Maintains test functionality while respecting the new access level
- …

fix: change the pointer object query method to internal method

---

contract/r/gnoswap/staker/staker.gno
contract/r/gnoswap/staker/staker_test.gno

This PR implements graceful degradation in the `CollectReward` function to handle cases where external incentive rewards are insufficient.
Instead of panicking and reverting the entire transaction, the function now emits an event and continues processing other rewards.
- Modified `CollectReward` to check if external incentive has sufficient rewards before transferring
- Ensures internal GNS rewards and other external incentives are still distributed even if one fails

feat(staker): Add Graceful Degradation to `CollectReward` for External Incentives

---

contract/r/gnoswap/gnft/gnft_test.gno
contract/r/gnoswap/gov/governance/_helper_test.gno
contract/r/gnoswap/gov/staker/_helper_test.gno
contract/r/gnoswap/pool/_helper_test.gno
contract/r/gnoswap/position/_helper_test.gno
contract/r/gnoswap/router/_helper_test.gno
contract/r/gnoswap/router/base.gno
contract/r/gnoswap/router/exact_in_test.gno
contract/r/gnoswap/router/protocol_fee_swap.gno
contract/r/gnoswap/router/router.gno
contract/r/gnoswap/router/router_test.gno
contract/r/gnoswap/router/swap_inner.gno
contract/r/gnoswap/router/wrap_unwrap.gno
tests/scenario/router/exact_out_swap_route_with_multi_route_filetest.gno
tests/scenario/router/exact_out_swap_route_with_single_route_filetest.gno

Removed the dependency on consts from the router contract. To minimize impact on other tasks, individual PRs will be created for each contract.

fix(router): Remove `consts` Dependencies from `Router` Contract

---

contract/r/gnoswap/gov/xgns/xgns.gno

Removed withdrawal halt validation from xGNS mint and burn operations to allow xGNS token management to function independently of withdrawal restrictions.
- **File**: `contract/r/gnoswap/gov/xgns/xgns.gno`
- **Updated Functions**:
- `Mint()` - Removed `halt.AssertIsNotHaltedWithdraw()`
- `MintByLaunchPad()` - Removed `halt.AssertIsNotHaltedWithdraw()`
- `Burn()` - Removed `halt.AssertIsNotHaltedWithdraw()`
- `BurnByLaunchPad()` - Removed `halt.AssertIsNotHaltedWithdraw()`
```go
func Mint(cur realm, to std.Address, amount int64) {
halt.AssertIsNotHaltedXGns()      // xGNS-specific halt
halt.AssertIsNotHaltedWithdraw()  // Withdrawal halt (REMOVED)
// ... mint logic
}
```
```go
func Mint(cur realm, to std.Address, amount int64) {
halt.AssertIsNotHaltedXGns()      // Only xGNS-specific halt …
```

feat(gov/xgns): remove withdrawal halt in gov/xgns

---

contract/p/gnoswap/rbac/ownable.gno

- Renamed the event in `TransferOwnership` from `OwnershipTransferEvent` to `OwnershipTransferStartedEvent`
- Modified `AcceptOwnership` to emit `OwnershipTransferEvent` when ownership is actually transferred
- Removed `OwnershipAcceptedEvent` as it was redundant with `OwnershipTransferEvent`
- Removed unused `AssertOwnedByOriginCaller` function

fix(p/rbac): Improved event naming clarity in Ownable

---

contract/r/gnoswap/gov/governance/consts.gno
contract/r/gnoswap/gov/governance/governance_execute.gno
contract/r/gnoswap/gov/governance/governance_propose.gno
contract/r/gnoswap/gov/governance/proposal.gno
contract/r/gnoswap/gov/governance/proposal_action_status.gno
contract/r/gnoswap/gov/governance/proposal_action_status_test.gno
contract/r/gnoswap/gov/governance/proposal_status.gno
contract/r/gnoswap/gov/governance/proposal_status_test.gno

- Removed success field from `ProposalActionStatus`
- Removed `IsSuccess()` method that was never called
- Removed `updateResult()` and `updateExecuteResult()` methods
- Since proposal execution either succeeds or panics, tracking success state was redundant
- Removed `halt.AssertIsNotHaltedWithdraw()` from `ProposeText` and `ProposeParameterChange` to follows the halt-checking documentation

fix(governance): Remove unnecessary `success` fields

---

contract/r/gnoswap/v1/staker/calculate_pool_position_reward.gno
contract/r/gnoswap/v1/staker/external_incentive.gno
contract/r/gnoswap/v1/staker/reward_calculation_incentives.gno
contract/r/gnoswap/v1/staker/reward_calculation_pool_tier.gno
contract/r/gnoswap/v1/staker/reward_calculation_types.gno
contract/r/gnoswap/v1/staker/type.gno
tests/scenario/staker/single_gns_external_ends_filetest.gno
tests/scenario/staker/staker_native_create_collect_unstake_filetest.gno

This PR migrates the external incentive system from block height-based calculations to timestamp-based calculations for more accurate and consistent reward distribution.
- **Modified `external_incentive.gno`**: 
- Changed incentive ID generation to use current timestamp instead of block height
- Improved variable consistency by storing `currentTime` and `currentHeight` once
- **Enhanced `reward_calculation_incentives.gno`**:
- Migrated from block height-based to timestamp-based unclaimable period tracking
- Added comprehensive documentation for the `Incentives` struct
- Implemented `calculateUnClaimableDuration` function for precise overlap calculations
- Improved unclaimable reward calculation logic with proper time range handling
- Removed unused function `calcPositionRewardByWarmups` …

fix: handle to time-based external reward

---

contract/r/gnoswap/v1/staker/reward_calculation_pool_tier_test.gno

This PR adds regression tests for the pool tier reward calculation system.
1. Re-enabled skipped `TestTierRatioFromCounts` test
2. Added more regression tests
- `TestTierRatioGet`: validates correct ratio retrieval for each tier
- `TestPoolTierChangeTier`:
- validates pool tier assignments are correctly updated
- Ratio recalculation when pools move between tiers
- `TestCurrentAllTierCounts`:
- Validates accurate counting of pools across all tiers
- Ensures the returned array correctly represent [tier0, tier1, tier2, tier3] counts
- `TestIsIniterallyIncentivizesPool`
- this test validates that:
1. pools in tier 1-3 are considered incentivized
2. pools not in any tier return false
- `TestCurrentRewardPerPool` 
- Validates:
1. Single tier scenario (100% to tier 1
2. Multi tier scenario (70% …

test(staker): Update Reward Calculation Pool Tier Tests

---

contract/r/gnoswap/v1/staker/reward_calculation_pool_tier.gno
contract/r/gnoswap/v1/staker/reward_calculation_pool_tier_test.gno

Optimizes the way `PoolTier` tracks the number of pools per tier.
Previously, methods like `CurrentAllTierCounts()` and `CurrentCount()` scanned the entire `membership` tree on every call. This made counting $O(n)$ with respect to the number of pools, even though counts only change when a pool moves tiers.
- Added a `counts` field to `PoolTier` as a cached counter
- Updated `changeTier()` to inc/dec the counts whenever a pool is added, removed or moved between tiers
- Updated `CurrentCount()` and `CurrentAllTierCounts()` to return results directly from the cached counter
By doing so, all tier count queries are now $o(1)$, avoiding repeated full-tree iteration.
dependent with #828

perf(staker): Optimize `PoolTier` counting with cached counters

---

contract/r/gnoswap/v1/gnft/gnft.gno
contract/r/gnoswap/v1/gnft/gnft_test.gno
contract/r/gnoswap/v1/position/README.md

The GNFT (Gnoswap NFT) contract was missing critical access control checks in its core transfer functions (`SafeTransferFrom` and `TransferFrom`). This security gap posed significant risks to the AMM (Automated Market Maker) system's stability and integrity.
**Before**: Transfer functions lacked proper access control
```go
func SafeTransferFrom(cur realm, from, to std.Address, tid grc721.TokenID) error {
halt.AssertIsNotHaltedPosition()
// Missing access control - any contract could call this
assertFromIsValidAddress(from)
assertToIsValidAddress(to)
// ... transfer logic
}
```
**After**: Strict access control implemented
```go
func SafeTransferFrom(cur realm, from, to std.Address, tid grc721.TokenID) error {
halt.AssertIsNotHaltedPosition()
caller := std.PreviousRealm().Address() …
```

fix: add missing GNFT transfer function access permission checks

---

contract/r/gnoswap/v1/common/grc20reg_helper.gno
contract/r/gnoswap/v1/community_pool/community_pool.gno
contract/r/gnoswap/v1/gov/staker/staker_reward.gno
contract/r/gnoswap/v1/launchpad/launchpad_project.gno
contract/r/gnoswap/v1/pool/pool.gno
contract/r/gnoswap/v1/pool/protocol_fee.gno
contract/r/gnoswap/v1/pool/transfer.gno
contract/r/gnoswap/v1/position/burn.gno
contract/r/gnoswap/v1/position/liquidity_management_test.gno
contract/r/gnoswap/v1/position/mint_test.gno
contract/r/gnoswap/v1/position/native_token_test.gno
contract/r/gnoswap/v1/position/position.gno
contract/r/gnoswap/v1/protocol_fee/state.gno
contract/r/gnoswap/v1/router/exact_in.gno
contract/r/gnoswap/v1/router/exact_out.gno
contract/r/gnoswap/v1/router/protocol_fee_swap.gno
contract/r/gnoswap/v1/router/protocol_fee_swap_test.gno
contract/r/gnoswap/v1/router/swap_inner.gno
contract/r/gnoswap/v1/staker/external_incentive.gno
contract/r/gnoswap/v1/staker/protocol_fee_unstaking.gno
contract/r/gnoswap/v1/staker/protocol_fee_unstaking_test.gno
contract/r/gnoswap/v1/staker/staker.gno

This PR addresses critical security vulnerabilities identified in the audit regarding unchecked GRC20 token transfers throughout the codebase. The implementation introduces Safe
transfer functions that validate transfer operations and revert on failure, ensuring atomicity and preventing state inconsistencies.
- **Added SafeGRC20 Helper Functions**: Introduced `SafeGRC20Transfer`, `SafeGRC20TransferFrom`, and `SafeGRC20Approve` in `grc20reg_helper.gno` that panic on transfer failures
- **Replaced All Unchecked Transfers**: Systematically replaced all `common.Transfer()` and `common.TransferFrom()` calls with their Safe counterparts across 16 contract files
- **Ensured State Consistency**: All token transfer operations now guarantee atomicity - either complete successfully or revert …

feat: handle transfer grc20 safe transfers

---

contract/r/gnoswap/v1/staker/reward_calculation_warmup.gno
contract/r/gnoswap/v1/staker/reward_calculation_warmup_test.gno

Added validation in the `modifyWarmup` function to ensure the last warmup tier always maintains `math.MaxInt64` duration.

fix(staker): Add validation to ensure last warmup tier maintains infinite duration

---

contract/r/gnoswap/v1/position/position.gno
contract/r/gnoswap/v1/protocol_fee/assert.gno
contract/r/gnoswap/v1/protocol_fee/protocol_fee.gno
contract/r/scenario/position/position_collect_fee_with_protocol_fee_filetest.gno

- Fix withdrawal fee tracking issue in position module where fees were transferred but
not tracked for distribution
- Add position contract to allowed callers for AddToProtocolFee function
- Ensure withdrawal fees collected from positions can be properly distributed through
the protocol fee mechanism
The `collectFee` function in the position module was transferring withdrawal fees
directly to the protocol fee address without calling `AddToProtocolFee`. This caused
these fees to become permanently inaccessible since the `DistributeProtocolFee`
function only distributes amounts tracked in the `tokenListWithAmount` mapping.
- Import `protocol_fee` package as `pf`
- Add `AddToProtocolFee` calls before transferring withdrawal fees to track them
properly
- Ensure both token0 and token1 …

fix: handle withdrawal fee when collect fee

---

contract/p/gnoswap/gnsmath/swap_math.gno

The `handleExactIn` and `handleExactOut` functions had inconsistent return values when partial price movements occurred:
- `handleExactIn`: In partial move scenarios, it was returning `amountRemainingLessFee` instead of the calculated `amountIn` to reach the target price
- `handleExactOut`: In partial move scenarios, it was returning `amountRemainingAbs` instead of the calculated `amountOut` for the target price
This inconsistency caused confusion about what these helper functions actually return and made the code harder to understand and maintain.
**Standardized return behavior:**
- Both functions now consistently return the amount needed to reach the target price (regardless of whether the target is actually reached)
- The caller (`SwapMathComputeSwapStep`) is responsible for …

fix(gnsmath): inconsistent return value in `handleExactIn` and `handleExactOut`

---

contract/r/gnoswap/v1/staker/reward_calculation_pool_tier.gno

Instead of explicitly updating the cache, I modified it to use the `cacheReward` function. Both approaches follow the same flow, and I confirmed that the previously problematic cases now pass.

fix: use cacheReward instead of exlicit cache update
